; ============================================================================
; PC-G815 compatible BIOS ROM (System ROM 0x8000-0xBFFF)
; ============================================================================

ORG 0x8000
ENTRY BIOS_BOOT_ENTRY

CHAR_CR    EQU 0x0D
CHAR_LF    EQU 0x0A

KEY_IN_PORT     EQU 0x1D
KEY_STROBE_PORT EQU 0x11
KEY_READ_PORT   EQU 0x10
LCD_CMD_DUAL    EQU 0x50
LCD_CMD_PORT    EQU 0x58
LCD_DATA_PORT   EQU 0x5A
LCD_CMD2_PORT   EQU 0x54
LCD_DATA2_PORT  EQU 0x56
LCD_READ_PORT   EQU 0x5B
LCD_READ2_PORT  EQU 0x57

LCD_VISIBLE_COLS EQU 24
LCD_VISIBLE_ROWS EQU 4
LCD_HALF_COLS    EQU 12
LCD_PAGE_COLS    EQU 72

RAM_DISPLAY_START_LINE EQU 0x790D
RAM_TEXT_COL           EQU 0x6FA8
RAM_TEXT_ROW           EQU 0x6FAD
RAM_TEXT_WRAP          EQU 0x6FAE

MONITOR_PROMPT_CURSOR_COL EQU 2
MONITOR_PROMPT_CURSOR_ROW EQU 2

  NOP
  NOP
  NOP

BIOS_JUMP_TABLE_START:
BIOS_BOOT_ENTRY:                 CALL BIOS_BOOT_WRAPPER
BIOS_MONITOR_MAIN_LOOP_ENTRY:    CALL BIOS_MONITOR_MAIN_LOOP_WRAPPER
BIOS_CHAR_PUT_ENTRY:             CALL BIOS_CHAR_PUT_WRAPPER
BIOS_CHAR_REPEAT_ENTRY:          CALL BIOS_CHAR_REPEAT_WRAPPER
BIOS_STRING_PUT_Z_ENTRY:         CALL BIOS_STRING_PUT_Z_WRAPPER
BIOS_GRAPHICS_WRITE_RAW_ENTRY:   CALL BIOS_GRAPHICS_WRITE_RAW_WRAPPER
BIOS_CRLF_ENTRY:                 CALL BIOS_CRLF_WRAPPER
BIOS_CLEAR_SCREEN_ENTRY:         CALL BIOS_CLEAR_SCREEN_WRAPPER
BIOS_SET_CURSOR_ENTRY:           CALL BIOS_SET_CURSOR_WRAPPER
BIOS_GET_GLYPH_PTR_ENTRY:        CALL BIOS_GET_GLYPH_PTR_WRAPPER
BIOS_INKEY_ENTRY:                CALL BIOS_INKEY_WRAPPER
BIOS_WAIT_KEY_ENTRY:             CALL BIOS_WAIT_KEY_WRAPPER
BIOS_GET_DISPLAY_START_ENTRY:    CALL BIOS_GET_DISPLAY_START_WRAPPER
BIOS_SET_DISPLAY_START_ENTRY:    CALL BIOS_SET_DISPLAY_START_WRAPPER
BIOS_SHUTDOWN_ENTRY:             CALL BIOS_SHUTDOWN_WRAPPER
BIOS_RESERVED_15_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_16_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_17_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_18_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_19_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_20_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_21_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_22_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_23_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_24_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_25_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_26_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_27_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_28_ENTRY:          CALL BIOS_RESERVED_WRAPPER
BIOS_RESERVED_29_ENTRY:          CALL BIOS_RESERVED_WRAPPER

BIOS_RETURN_FROM_ENTRY:
  INC SP
  INC SP
  RET

BIOS_RESERVED_WRAPPER:
  JP BIOS_RETURN_FROM_ENTRY

BIOS_BOOT_WRAPPER:
  CALL BIOS_BOOT
  JP BIOS_RETURN_FROM_ENTRY

BIOS_MONITOR_MAIN_LOOP_WRAPPER:
  JP BIOS_MONITOR_MAIN_LOOP

BIOS_CHAR_PUT_WRAPPER:
  CALL BIOS_OUT_CHAR
  JP BIOS_RETURN_FROM_ENTRY

BIOS_CHAR_REPEAT_WRAPPER:
  CALL BIOS_OUT_REPEAT
  JP BIOS_RETURN_FROM_ENTRY

BIOS_STRING_PUT_Z_WRAPPER:
  CALL BIOS_PRINT_STRING_Z
  JP BIOS_RETURN_FROM_ENTRY

BIOS_GRAPHICS_WRITE_RAW_WRAPPER:
  CALL BIOS_LCD_WRITE_RAW_BYTE
  JP BIOS_RETURN_FROM_ENTRY

BIOS_CRLF_WRAPPER:
  CALL BIOS_PRINT_CRLF
  JP BIOS_RETURN_FROM_ENTRY

BIOS_CLEAR_SCREEN_WRAPPER:
  CALL BIOS_LCD_CLEAR_SCREEN
  JP BIOS_RETURN_FROM_ENTRY

BIOS_SET_CURSOR_WRAPPER:
  CALL BIOS_LCD_SET_CURSOR_DE
  JP BIOS_RETURN_FROM_ENTRY

BIOS_GET_GLYPH_PTR_WRAPPER:
  CALL BIOS_LCD_GET_GLYPH_PTR
  JP BIOS_RETURN_FROM_ENTRY

BIOS_INKEY_WRAPPER:
  IN A,(KEY_IN_PORT)
  JP BIOS_RETURN_FROM_ENTRY

BIOS_WAIT_KEY_WRAPPER:
BIOS_WAIT_KEY_LOOP:
  IN A,(KEY_IN_PORT)
  OR A
  JR Z,BIOS_WAIT_KEY_LOOP
  JP BIOS_RETURN_FROM_ENTRY

BIOS_GET_DISPLAY_START_WRAPPER:
  LD A,(RAM_DISPLAY_START_LINE)
  JP BIOS_RETURN_FROM_ENTRY

BIOS_SET_DISPLAY_START_WRAPPER:
  AND 0x1F
  LD (RAM_DISPLAY_START_LINE),A
  OR 0xC0
  OUT (LCD_CMD_DUAL),A
  JP BIOS_RETURN_FROM_ENTRY

BIOS_SHUTDOWN_WRAPPER:
  HALT
  JP BIOS_RETURN_FROM_ENTRY

BIOS_COLD_BOOT_ADDR:
MONITOR_PROMPT_RESUME_ADDR:
BIOS_BOOT:
  LD SP,0x7FFF
  CALL BIOS_LCD_CLEAR_SCREEN
  XOR A
  LD D,A
  LD E,A
  CALL BIOS_LCD_SET_CURSOR_DE
  LD HL,BOOT_LINE_0
  CALL BIOS_PRINT_STRING_Z
  CALL BIOS_PRINT_CRLF
  LD HL,BOOT_LINE_1
  CALL BIOS_PRINT_STRING_Z
  CALL BIOS_PRINT_CRLF
  LD HL,BOOT_LINE_2
  CALL BIOS_PRINT_STRING_Z
  LD D,MONITOR_PROMPT_CURSOR_ROW
  LD E,MONITOR_PROMPT_CURSOR_COL
  CALL BIOS_LCD_SET_CURSOR_DE
  JP BIOS_MONITOR_MAIN_LOOP

MONITOR_MAIN_LOOP_ADDR:
BIOS_MONITOR_MAIN_LOOP:
  LD A,0xFF
  OUT (KEY_STROBE_PORT),A
  IN A,(KEY_READ_PORT)
  JR BIOS_MONITOR_MAIN_LOOP

BIOS_OUT_REPEAT:
  LD C,A
BIOS_OUT_REPEAT_LOOP:
  LD A,B
  OR A
  RET Z
  LD A,C
  PUSH BC
  CALL BIOS_OUT_CHAR
  POP BC
  DEC B
  JR BIOS_OUT_REPEAT_LOOP

BIOS_OUT_CHAR:
  PUSH AF
  PUSH BC
  PUSH DE
  PUSH HL
  LD B,A
  CP CHAR_CR
  JR Z,BIOS_OUT_CHAR_CR
  CP CHAR_LF
  JR Z,BIOS_OUT_CHAR_LF
  CP 0x08
  JR Z,BIOS_OUT_CHAR_BS

  LD A,(RAM_TEXT_WRAP)
  OR A
  CALL NZ,BIOS_LCD_APPLY_PENDING_WRAP

  LD A,B
  CALL BIOS_LCD_DRAW_CHAR_AT_CURSOR
  CALL BIOS_LCD_ADVANCE_CURSOR
  JR BIOS_OUT_CHAR_DONE

BIOS_OUT_CHAR_CR:
  XOR A
  LD (RAM_TEXT_COL),A
  LD (RAM_TEXT_WRAP),A
  JR BIOS_OUT_CHAR_DONE

BIOS_OUT_CHAR_LF:
  LD A,(RAM_TEXT_ROW)
  CP LCD_VISIBLE_ROWS - 1
  JR C,BIOS_OUT_CHAR_LF_NEXT
  CALL BIOS_LCD_SCROLL_UP_ONE_ROW
  XOR A
  LD (RAM_TEXT_WRAP),A
  JR BIOS_OUT_CHAR_DONE
BIOS_OUT_CHAR_LF_NEXT:
  INC A
  LD (RAM_TEXT_ROW),A
  XOR A
  LD (RAM_TEXT_WRAP),A
  JR BIOS_OUT_CHAR_DONE

BIOS_OUT_CHAR_BS:
  LD A,(RAM_TEXT_WRAP)
  OR A
  JR NZ,BIOS_OUT_CHAR_BS_CANCEL_WRAP
  LD A,(RAM_TEXT_COL)
  OR A
  JR Z,BIOS_OUT_CHAR_BS_CLEAR
  DEC A
  LD (RAM_TEXT_COL),A
BIOS_OUT_CHAR_BS_CLEAR:
  XOR A
  LD (RAM_TEXT_WRAP),A
  CALL BIOS_LCD_CLEAR_CELL_AT_CURSOR
  JR BIOS_OUT_CHAR_DONE
BIOS_OUT_CHAR_BS_CANCEL_WRAP:
  XOR A
  LD (RAM_TEXT_WRAP),A

BIOS_OUT_CHAR_DONE:
  POP HL
  POP DE
  POP BC
  POP AF
  RET

BIOS_PRINT_CRLF:
  LD A,CHAR_CR
  CALL BIOS_OUT_CHAR
  LD A,CHAR_LF
  CALL BIOS_OUT_CHAR
  RET

BIOS_PRINT_STRING_Z:
BIOS_PRINT_STRING_Z_LOOP:
  LD A,(HL)
  OR A
  RET Z
  CALL BIOS_OUT_CHAR
  INC HL
  JR BIOS_PRINT_STRING_Z_LOOP

BIOS_LCD_SET_CURSOR_HOME:
  XOR A
  LD (RAM_TEXT_COL),A
  LD (RAM_TEXT_ROW),A
  LD (RAM_TEXT_WRAP),A
  RET

BIOS_LCD_SET_CURSOR_DE:
  LD A,E
  LD (RAM_TEXT_COL),A
  LD A,D
  LD (RAM_TEXT_ROW),A
  XOR A
  LD (RAM_TEXT_WRAP),A
  RET

BIOS_LCD_ADVANCE_CURSOR:
  LD A,(RAM_TEXT_COL)
  CP LCD_VISIBLE_COLS - 1
  JR C,BIOS_LCD_ADVANCE_CURSOR_INC
  LD A,1
  LD (RAM_TEXT_WRAP),A
  RET
BIOS_LCD_ADVANCE_CURSOR_INC:
  INC A
  LD (RAM_TEXT_COL),A
  RET

BIOS_LCD_APPLY_PENDING_WRAP:
  XOR A
  LD (RAM_TEXT_COL),A
  LD (RAM_TEXT_WRAP),A
  LD A,(RAM_TEXT_ROW)
  CP LCD_VISIBLE_ROWS - 1
  JR C,BIOS_LCD_APPLY_PENDING_WRAP_NEXT
  CALL BIOS_LCD_SCROLL_UP_ONE_ROW
  RET
BIOS_LCD_APPLY_PENDING_WRAP_NEXT:
  INC A
  LD (RAM_TEXT_ROW),A
  RET

BIOS_LCD_CLEAR_SCREEN:
  LD C,0
BIOS_LCD_CLEAR_SCREEN_PAGE_LOOP:
  LD B,0
BIOS_LCD_CLEAR_SCREEN_COL_LOOP:
  XOR A
  PUSH BC
  CALL BIOS_LCD_WRITE_RAW_BYTE
  POP BC
  INC B
  LD A,B
  CP LCD_PAGE_COLS
  JR C,BIOS_LCD_CLEAR_SCREEN_COL_LOOP
  INC C
  LD A,C
  CP 8
  JR C,BIOS_LCD_CLEAR_SCREEN_PAGE_LOOP
  JP BIOS_LCD_SET_CURSOR_HOME

BIOS_LCD_CLEAR_CELL_AT_CURSOR:
  LD B,0
BIOS_LCD_CLEAR_CELL_AT_CURSOR_LOOP:
  XOR A
  PUSH BC
  CALL BIOS_LCD_WRITE_GLYPH_COLUMN_FROM_CURSOR
  POP BC
  INC B
  LD A,B
  CP 6
  JR C,BIOS_LCD_CLEAR_CELL_AT_CURSOR_LOOP
  RET

BIOS_LCD_DRAW_CHAR_AT_CURSOR:
  PUSH AF
  CALL BIOS_LCD_GET_GLYPH_PTR
  LD B,0
BIOS_LCD_DRAW_CHAR_LOOP:
  LD A,(HL)
  PUSH HL
  PUSH BC
  CALL BIOS_LCD_WRITE_GLYPH_COLUMN_FROM_CURSOR
  POP BC
  POP HL
  INC HL
  INC B
  LD A,B
  CP 5
  JR C,BIOS_LCD_DRAW_CHAR_LOOP
  XOR A
  CALL BIOS_LCD_WRITE_GLYPH_COLUMN_FROM_CURSOR
  POP AF
  RET

BIOS_LCD_WRITE_GLYPH_COLUMN_FROM_CURSOR:
  PUSH AF
  LD D,B
  LD A,(RAM_TEXT_COL)
  CP LCD_HALF_COLS
  JR C,BIOS_LCD_WRITE_GLYPH_COLUMN_LEFT

  ADD A,A
  LD B,A
  ADD A,A
  ADD A,B
  LD B,A
  LD A,143
  SUB B
  SUB D
  LD B,A
  LD A,(RAM_TEXT_ROW)
  ADD A,4
  LD C,A
  POP AF
  JP BIOS_LCD_WRITE_RAW_BYTE

BIOS_LCD_WRITE_GLYPH_COLUMN_LEFT:
  ADD A,A
  LD B,A
  ADD A,A
  ADD A,B
  ADD A,D
  LD B,A
  LD A,(RAM_TEXT_ROW)
  LD C,A
  POP AF
  JP BIOS_LCD_WRITE_RAW_BYTE

BIOS_LCD_GET_GLYPH_PTR:
  LD E,A
  LD D,0
  LD L,A
  LD H,0
  ADD HL,HL
  ADD HL,HL
  ADD HL,DE
  LD DE,FONT5X7_TABLE
  ADD HL,DE
  RET

BIOS_LCD_READ_RAW_BYTE:
  PUSH BC
  LD A,B
  CP 60
  JR C,BIOS_LCD_READ_RAW_BYTE_SECONDARY
  SUB 60
  OR 0x40
  OUT (LCD_CMD_PORT),A
  LD A,C
  OR 0x80
  OUT (LCD_CMD_PORT),A
  IN A,(LCD_READ_PORT)
  IN A,(LCD_READ_PORT)
  POP BC
  RET
BIOS_LCD_READ_RAW_BYTE_SECONDARY:
  OR 0x40
  OUT (LCD_CMD2_PORT),A
  LD A,C
  OR 0x80
  OUT (LCD_CMD2_PORT),A
  IN A,(LCD_READ2_PORT)
  IN A,(LCD_READ2_PORT)
  POP BC
  RET

BIOS_LCD_WRITE_RAW_BYTE:
  PUSH AF
  LD A,B
  CP 60
  JR C,BIOS_LCD_WRITE_RAW_BYTE_SECONDARY
  SUB 60
  OR 0x40
  OUT (LCD_CMD_PORT),A
  LD A,C
  OR 0x80
  OUT (LCD_CMD_PORT),A
  POP AF
  OUT (LCD_DATA_PORT),A
  RET
BIOS_LCD_WRITE_RAW_BYTE_SECONDARY:
  OR 0x40
  OUT (LCD_CMD2_PORT),A
  LD A,C
  OR 0x80
  OUT (LCD_CMD2_PORT),A
  POP AF
  OUT (LCD_DATA2_PORT),A
  RET

BIOS_LCD_COPY_PAGE:
  LD B,0
BIOS_LCD_COPY_PAGE_LOOP:
  PUSH BC
  LD C,E
  CALL BIOS_LCD_READ_RAW_BYTE
  LD C,D
  CALL BIOS_LCD_WRITE_RAW_BYTE
  POP BC
  INC B
  LD A,B
  CP LCD_PAGE_COLS
  JR C,BIOS_LCD_COPY_PAGE_LOOP
  RET

BIOS_LCD_CLEAR_PAGE:
  LD B,0
BIOS_LCD_CLEAR_PAGE_LOOP:
  XOR A
  PUSH BC
  CALL BIOS_LCD_WRITE_RAW_BYTE
  POP BC
  INC B
  LD A,B
  CP LCD_PAGE_COLS
  JR C,BIOS_LCD_CLEAR_PAGE_LOOP
  RET

BIOS_LCD_SCROLL_UP_ONE_ROW:
  LD D,0
  LD E,1
  CALL BIOS_LCD_COPY_PAGE
  LD D,1
  LD E,2
  CALL BIOS_LCD_COPY_PAGE
  LD D,2
  LD E,3
  CALL BIOS_LCD_COPY_PAGE
  LD C,3
  CALL BIOS_LCD_CLEAR_PAGE
  LD D,4
  LD E,5
  CALL BIOS_LCD_COPY_PAGE
  LD D,5
  LD E,6
  CALL BIOS_LCD_COPY_PAGE
  LD D,6
  LD E,7
  CALL BIOS_LCD_COPY_PAGE
  LD C,7
  CALL BIOS_LCD_CLEAR_PAGE
  LD A,LCD_VISIBLE_ROWS - 1
  LD (RAM_TEXT_ROW),A
  XOR A
  LD (RAM_TEXT_WRAP),A
  RET

BOOT_LINE_0:
  DB "PC-G815 COMPAT",0
BOOT_LINE_1:
  DB "BASIC READY",0
BOOT_LINE_2:
  DB "> ",0

INCLUDE "generated_font5x7.asm"

END
