; ============================================================================
; PC-G815 BASIC Z80インタープリター本体 (ROM 0xC000-0xFFFF)
; --------------------------------------------------------------------------
; 役割:
;   - Web/UI から投入された BASIC テキストを Z80 命令で受け取り、
;     行保存・コマンド判定・実行ループを行う。
;   - コアコードは banked ROM 窓 0xC000-0xFFFF で実行する。
; 入力:
;   - IN 0x1D から文字入力。0x04(EOT) で入力終了。
; 出力:
;   - OUT 0x5A でLCD表示、必要に応じて I/O ポート制御。
; 副作用:
;   - RAM 0x4000-0x6FFF のみをBASIC作業領域として利用。
; 異常時:
;   - メモリ不足時は RAM_LAST_ERROR に 1 を設定し、行保存を中断。
; ============================================================================

ORG 0xC000
ENTRY BASIC_ENTRY

; ----------------------------------------------------------------------------
; ルーチン: BASIC_ENTRY
; 役割:
;   - バンク切替直後に必ず 0xC000 から開始できるよう固定入口にする。
;   - 実本体は BASIC_MAIN_ENTRY へジャンプして実行する。
; ----------------------------------------------------------------------------
BASIC_ENTRY:
  JP BASIC_MAIN_ENTRY

; -------------------------------
; I/O ポート定義
; -------------------------------
IN_PORT      EQU 0x1D
LCD_PORT     EQU 0x5A
LCD_CMD_PORT EQU 0x58
LCD_PORT2    EQU 0x56
LCD_CMD2_PORT EQU 0x54
LCD_READ_PORT EQU 0x5B
LCD_READ2_PORT EQU 0x57

; -------------------------------
; 文字コード
; -------------------------------
CHAR_CR    EQU 0x0D
CHAR_LF    EQU 0x0A
CHAR_SPACE EQU 0x20
CHAR_COLON EQU 0x3A
CHAR_0     EQU 0x30
CHAR_9     EQU 0x39
CHAR_EOT   EQU 0x04

; -------------------------------
; RAM 利用範囲
; -------------------------------
RAM_BASIC_START EQU 0x4000
RAM_BASIC_END   EQU 0x6FFF

; 可変領域の管理方針:
; ProgramArea は 0x4000 から上方向へ伸長する。
; 0x6C00 以降は管理変数・バッファ用に固定確保し、
; ProgramArea の上限を 0x6BFF とする。
RAM_PROG_START     EQU 0x4000
RAM_PROG_LIMIT     EQU 0x6BFF
RAM_PROG_LIMIT_NEXT EQU 0x6C00

; 管理変数・バッファ
RAM_LINEBUF      EQU 0x6E00
MAX_LINE_LEN     EQU 200

RAM_LINE_LEN     EQU 0x6EF0
RAM_FLAG_EOT     EQU 0x6EF1
RAM_PROG_PTR_LO  EQU 0x6EF2
RAM_PROG_PTR_HI  EQU 0x6EF3
RAM_CMDPTR_LO    EQU 0x6EF4
RAM_CMDPTR_HI    EQU 0x6EF5
RAM_MATCH_ID     EQU 0x6EF6
RAM_LAST_ERROR   EQU 0x6EF7
RAM_RUN_PTR_LO      EQU 0x6EF8
RAM_RUN_PTR_HI      EQU 0x6EF9
RAM_NEXT_PTR_LO     EQU 0x6EFA
RAM_NEXT_PTR_HI     EQU 0x6EFB
RAM_EXEC_STOP       EQU 0x6EFC
RAM_JUMP_FLAG       EQU 0x6EFD
RAM_JUMP_LINE_LO    EQU 0x6EFE
RAM_JUMP_LINE_HI    EQU 0x6EFF

RAM_AFTER_CMD_LO    EQU 0x6F00
RAM_AFTER_CMD_HI    EQU 0x6F01
RAM_PTR_OVERRIDE    EQU 0x6F02
RAM_OVERRIDE_LO     EQU 0x6F03
RAM_OVERRIDE_HI     EQU 0x6F04
RAM_GOSUB_SP        EQU 0x6F05
RAM_FOR_SP          EQU 0x6F06
RAM_EXPR_PTR_LO     EQU 0x6F07
RAM_EXPR_PTR_HI     EQU 0x6F08
RAM_TMP_KEY1        EQU 0x6F09
RAM_TMP_KEY2        EQU 0x6F0A
RAM_TMP_KEY3        EQU 0x6F0B
RAM_TMP_VAL_LO      EQU 0x6F0C
RAM_TMP_VAL_HI      EQU 0x6F0D
RAM_CMP_OP          EQU 0x6F0E

RAM_GOSUB_STACK     EQU 0x6F10
GOSUB_MAX_DEPTH     EQU 16
RAM_FOR_STACK       EQU 0x6F30
FOR_MAX_DEPTH       EQU 4
FOR_FRAME_SIZE      EQU 9

RAM_PRINT_DIGITS    EQU 0x6F60
RAM_AUTO_FLAG       EQU 0x6F61
RAM_AUTO_STEP_LO    EQU 0x6F62
RAM_AUTO_STEP_HI    EQU 0x6F63
RAM_AUTO_NEXT_LO    EQU 0x6F64
RAM_AUTO_NEXT_HI    EQU 0x6F65
RAM_PAUSE_FLAG      EQU 0x6F66
RAM_PAUSE_PTR_LO    EQU 0x6F67
RAM_PAUSE_PTR_HI    EQU 0x6F68
RAM_REPEAT_FLAG     EQU 0x6F69
RAM_REPEAT_PTR_LO   EQU 0x6F6A
RAM_REPEAT_PTR_HI   EQU 0x6F6B
RAM_DATA_COUNT      EQU 0x6F6C
RAM_DATA_INDEX      EQU 0x6F6D
RAM_DATA_SCAN_LO    EQU 0x6F6E
RAM_DATA_SCAN_HI    EQU 0x6F6F
RAM_ASSIGN_KEY1     EQU 0x6F70
RAM_ASSIGN_KEY2     EQU 0x6F71
RAM_ASSIGN_KEY3     EQU 0x6F72
RAM_FIND_CACHE_VALID   EQU 0x6F73
RAM_FIND_CACHE_LINE_LO EQU 0x6F74
RAM_FIND_CACHE_LINE_HI EQU 0x6F75
RAM_FIND_CACHE_PTR_LO  EQU 0x6F76
RAM_FIND_CACHE_PTR_HI  EQU 0x6F77
RAM_VAR_CACHE_VALID    EQU 0x6F78
RAM_VAR_CACHE_KEY1     EQU 0x6F79
RAM_VAR_CACHE_KEY2     EQU 0x6F7A
RAM_VAR_CACHE_KEY3     EQU 0x6F7B
RAM_VAR_CACHE_PTR_LO   EQU 0x6F7C
RAM_VAR_CACHE_PTR_HI   EQU 0x6F7D
RAM_RND_SEED_LO        EQU 0x6F7E
RAM_RND_SEED_HI        EQU 0x6F7F
RAM_DATA_VALUES     EQU 0x6F80
DATA_MAX_VALUES     EQU 16
RAM_FILE_COUNT      EQU 0x6FA0
RAM_FILE_TMP        EQU 0x6FA1
RAM_LABEL_CACHE_VALID   EQU 0x6FA2
RAM_LABEL_CACHE_KEY1    EQU 0x6FA3
RAM_LABEL_CACHE_KEY2    EQU 0x6FA4
RAM_LABEL_CACHE_KEY3    EQU 0x6FA5
RAM_LABEL_CACHE_PTR_LO  EQU 0x6FA6
RAM_LABEL_CACHE_PTR_HI  EQU 0x6FA7
RAM_TEXT_COL            EQU 0x6FA8
RAM_INPUT_FLAGS         EQU 0x6FA9
RAM_INPUT_PROMPT_LEN    EQU 0x6FAA
RAM_INPUT_DELIM         EQU 0x6FAB
RAM_INPUT_ECHO          EQU 0x6FAC
RAM_TEXT_ROW            EQU 0x6FAD
RAM_TEXT_WRAP           EQU 0x6FAE
RAM_IF_SKIP_LINE        EQU 0x6FAF
RAM_FILE_TABLE      EQU 0x6FB1
FILE_NAME_MAX       EQU 15
FILE_MAX_ENTRIES    EQU 4
RAM_VAR_TABLE       EQU 0x6C00
VAR_ENTRY_SIZE      EQU 6
VAR_MAX_ENTRIES     EQU 64

INCLUDE "command_tokens.asm"
INCLUDE "line_input.asm"
INCLUDE "generated_font5x7.asm"
INCLUDE "runtime_io.asm"
INCLUDE "program_store.asm"
INCLUDE "runtime_exec.asm"
INCLUDE "tokenizer.asm"
INCLUDE "parser.asm"
INCLUDE "expr_vm.asm"
INCLUDE "runtime_file.asm"
INCLUDE "runtime_graphics.asm"
INCLUDE "runtime_machine.asm"

END
