; ============================================================================
; 実行ループ / 命令ディスパッチ
; ----------------------------------------------------------------------------
; 役割:
;   - 入力行を保存または即時実行へ振り分ける。
;   - RUN 時は ProgramArea から各行を取り出して Z80 上で解釈実行する。
; ============================================================================

TOKEN_THEN:
  DB "THEN",0
TOKEN_TO:
  DB "TO",0
TOKEN_STEP:
  DB "STEP",0
TOKEN_USING:
  DB "USING",0

; ----------------------------------------------------------------------------
; ルーチン: BASIC_MAIN_ENTRY
; 役割: インタープリターのエントリーポイント。
; ----------------------------------------------------------------------------
BASIC_MAIN_ENTRY:
  CALL INIT_INTERPRETER

BASIC_MAIN_LOOP:
  CALL READ_LINE
  LD A,(RAM_FLAG_EOT)
  OR A
  RET NZ

  CALL PROCESS_LINE
  JR BASIC_MAIN_LOOP

; ----------------------------------------------------------------------------
; ルーチン: INIT_INTERPRETER
; 役割: 起動時初期化。
; ----------------------------------------------------------------------------
INIT_INTERPRETER:
  CALL CLEAR_PROGRAM
  CALL CLEAR_VARIABLE_TABLE
  CALL CLEAR_FILE_TABLE
  XOR A
  LD (RAM_LINE_LEN),A
  LD (RAM_FLAG_EOT),A
  LD (RAM_EXEC_STOP),A
  LD (RAM_JUMP_FLAG),A
  LD (RAM_PTR_OVERRIDE),A
  LD (RAM_AUTO_FLAG),A
  LD (RAM_PAUSE_FLAG),A
  LD (RAM_REPEAT_FLAG),A
  LD (RAM_DATA_COUNT),A
  LD (RAM_DATA_INDEX),A
  LD (RAM_LABEL_CACHE_VALID),A
  LD (RAM_TEXT_COL),A
  LD A,0x2B
  LD (RAM_RND_SEED_LO),A
  LD A,0x4D
  LD (RAM_RND_SEED_HI),A
  RET

; ----------------------------------------------------------------------------
; ルーチン: PROCESS_LINE
; 役割: 入力済み行を保存または実行へ振り分ける。
; ----------------------------------------------------------------------------
PROCESS_LINE:
  LD A,(RAM_LINE_LEN)
  OR A
  RET Z

  LD HL,RAM_LINEBUF
  CALL SKIP_SPACES
  CALL SET_CMDPTR_FROM_HL

  LD A,(HL)
  OR A
  RET Z

  CALL IS_DIGIT
  JR C,PROCESS_PROGRAM_LINE
  CP '*'
  JR Z,PROCESS_PROGRAM_LINE

  CALL EXECUTE_IMMEDIATE
  RET

PROCESS_PROGRAM_LINE:
  CALL APPEND_PROGRAM_LINE
  RET

; ----------------------------------------------------------------------------
; ルーチン: EXECUTE_IMMEDIATE
; 役割: 即時入力行を1文として実行する。
; ----------------------------------------------------------------------------
EXECUTE_IMMEDIATE:
  CALL EXECUTE_COMMAND_AT_CMDPTR
  RET

; ----------------------------------------------------------------------------
; ルーチン: RUN_STORED_PROGRAM
; 役割: ProgramArea を先頭から順次実行する。
; ----------------------------------------------------------------------------
RUN_STORED_PROGRAM:
  XOR A
  LD (RAM_EXEC_STOP),A
  LD (RAM_JUMP_FLAG),A
  LD (RAM_PTR_OVERRIDE),A
  LD (RAM_LAST_ERROR),A

  LD A,0x00
  LD (RAM_RUN_PTR_LO),A
  LD A,0x40
  LD (RAM_RUN_PTR_HI),A
  XOR A
  LD (RAM_TMP_VAL_LO),A
  LD (RAM_TMP_VAL_HI),A

RUN_PROGRAM_MAIN_LOOP:
  CALL IS_RUN_PTR_AT_END
  RET Z

  CALL LOAD_CURRENT_RECORD
  CALL EXECUTE_COMMAND_AT_CMDPTR

  LD A,(RAM_EXEC_STOP)
  OR A
  RET NZ

  LD A,(RAM_PTR_OVERRIDE)
  OR A
  JR Z,RUN_PROGRAM_CHECK_JUMP
  XOR A
  LD (RAM_PTR_OVERRIDE),A
  LD A,(RAM_OVERRIDE_LO)
  LD (RAM_RUN_PTR_LO),A
  LD A,(RAM_OVERRIDE_HI)
  LD (RAM_RUN_PTR_HI),A
  JR RUN_PROGRAM_MAIN_LOOP

RUN_PROGRAM_CHECK_JUMP:
  LD A,(RAM_JUMP_FLAG)
  OR A
  JR Z,RUN_PROGRAM_NEXT_LINEAR
  XOR A
  LD (RAM_JUMP_FLAG),A
  LD A,(RAM_JUMP_LINE_LO)
  LD E,A
  LD A,(RAM_JUMP_LINE_HI)
  LD D,A
  CALL FIND_LINE_BY_NUMBER
  JR C,RUN_PROGRAM_MAIN_LOOP
  LD A,2
  LD (RAM_LAST_ERROR),A
  RET

RUN_PROGRAM_NEXT_LINEAR:
  LD A,(RAM_NEXT_PTR_LO)
  LD (RAM_RUN_PTR_LO),A
  LD A,(RAM_NEXT_PTR_HI)
  LD (RAM_RUN_PTR_HI),A
  JR RUN_PROGRAM_MAIN_LOOP

; ----------------------------------------------------------------------------
; ルーチン: IS_RUN_PTR_AT_END
; 役割: 現在実行ポインタが末尾に到達したか判定する。
; 出力: Z=1 到達済み, Z=0 継続
; ----------------------------------------------------------------------------
IS_RUN_PTR_AT_END:
  LD A,(RAM_RUN_PTR_LO)
  LD E,A
  LD A,(RAM_RUN_PTR_HI)
  LD D,A
  LD A,(RAM_PROG_PTR_LO)
  CP E
  JR NZ,IS_RUN_PTR_AT_END_NO
  LD A,(RAM_PROG_PTR_HI)
  CP D
  JR NZ,IS_RUN_PTR_AT_END_NO
  XOR A
  RET
IS_RUN_PTR_AT_END_NO:
  LD A,1
  OR A
  RET

; ----------------------------------------------------------------------------
; ルーチン: LOAD_CURRENT_RECORD
; 役割:
;   - RAM_RUN_PTR が指すレコードを RAM_LINEBUF へコピーする。
;   - RAM_NEXT_PTR に次レコード先頭を保存する。
;   - RAM_CMDPTR を「行番号の後ろ(文頭)」へ設定する。
; ----------------------------------------------------------------------------
LOAD_CURRENT_RECORD:
  LD A,(RAM_RUN_PTR_LO)
  LD E,A
  LD A,(RAM_RUN_PTR_HI)
  LD D,A

  LD A,(DE)
  LD B,A
  INC DE

  LD HL,RAM_LINEBUF
LOAD_CURRENT_RECORD_COPY:
  LD A,B
  OR A
  JR Z,LOAD_CURRENT_RECORD_COPY_DONE
  LD A,(DE)
  LD (HL),A
  INC DE
  INC HL
  DEC B
  JR LOAD_CURRENT_RECORD_COPY

LOAD_CURRENT_RECORD_COPY_DONE:
  XOR A
  LD (HL),A

  LD A,E
  LD (RAM_NEXT_PTR_LO),A
  LD A,D
  LD (RAM_NEXT_PTR_HI),A

  LD HL,RAM_LINEBUF
  CALL SKIP_SPACES
  CALL PARSE_LINE_NUMBER_FROM_HL
  JR NC,LOAD_CURRENT_RECORD_NO_LINE
  CALL SKIP_SPACES
LOAD_CURRENT_RECORD_NO_LINE:
  CALL SET_CMDPTR_FROM_HL
  RET

; ----------------------------------------------------------------------------
; ルーチン: FIND_LINE_BY_NUMBER
; 役割: ProgramArea から行番号 DE に一致するレコードを探索する。
; 出力: Carry=1 発見, RAM_RUN_PTR を更新
;       Carry=0 未発見
; ----------------------------------------------------------------------------
FIND_LINE_BY_NUMBER:
  LD A,E
  LD (RAM_TMP_VAL_LO),A
  LD A,D
  LD (RAM_TMP_VAL_HI),A
  LD A,(RAM_FIND_CACHE_VALID)
  OR A
  JR Z,FIND_LINE_SCAN_FROM_TOP
  LD A,(RAM_FIND_CACHE_LINE_LO)
  CP E
  JR NZ,FIND_LINE_SCAN_FROM_TOP
  LD A,(RAM_FIND_CACHE_LINE_HI)
  CP D
  JR NZ,FIND_LINE_SCAN_FROM_TOP
  LD A,(RAM_FIND_CACHE_PTR_LO)
  LD (RAM_RUN_PTR_LO),A
  LD A,(RAM_FIND_CACHE_PTR_HI)
  LD (RAM_RUN_PTR_HI),A
  SCF
  RET

FIND_LINE_SCAN_FROM_TOP:
  LD BC,RAM_PROG_START
FIND_LINE_LOOP:
  LD A,(RAM_PROG_PTR_LO)
  CP C
  JR NZ,FIND_LINE_HAS_RECORD
  LD A,(RAM_PROG_PTR_HI)
  CP B
  JR Z,FIND_LINE_NOT_FOUND

FIND_LINE_HAS_RECORD:
  LD A,(BC)
  LD E,A
  INC BC
  PUSH BC
  PUSH DE
  LD H,B
  LD L,C
  CALL PARSE_LINE_NUMBER_FROM_HL
  JR NC,FIND_LINE_SKIP_COMPARE

  LD A,(RAM_TMP_VAL_LO)
  CP E
  JR NZ,FIND_LINE_SKIP_COMPARE
  LD A,(RAM_TMP_VAL_HI)
  CP D
  JR NZ,FIND_LINE_SKIP_COMPARE

  POP DE
  POP BC
  DEC BC
  LD A,C
  LD (RAM_RUN_PTR_LO),A
  LD A,B
  LD (RAM_RUN_PTR_HI),A
  LD A,1
  LD (RAM_FIND_CACHE_VALID),A
  LD A,(RAM_TMP_VAL_LO)
  LD (RAM_FIND_CACHE_LINE_LO),A
  LD A,(RAM_TMP_VAL_HI)
  LD (RAM_FIND_CACHE_LINE_HI),A
  LD A,C
  LD (RAM_FIND_CACHE_PTR_LO),A
  LD A,B
  LD (RAM_FIND_CACHE_PTR_HI),A
  SCF
  RET

FIND_LINE_SKIP_COMPARE:
  POP DE
  POP BC
  DEC BC

  ; BC = BC + 1 + length
  LD HL,1
  ADD HL,BC
  LD A,E
  LD E,A
  LD D,0
  ADD HL,DE
  LD B,H
  LD C,L
  JR FIND_LINE_LOOP

FIND_LINE_NOT_FOUND:
  AND A
  RET

; ----------------------------------------------------------------------------
; ルーチン: EXECUTE_COMMAND_AT_CMDPTR
; 役割: RAM_CMDPTR の1文を分類し、対応ハンドラを呼ぶ。
; ----------------------------------------------------------------------------
EXECUTE_COMMAND_AT_CMDPTR:
  CALL GET_CMDPTR_HL
  CALL SKIP_SPACES
  CALL SET_CMDPTR_FROM_HL
  LD A,(HL)
  OR A
  RET Z
  CP '*'
  JR Z,EXECUTE_SKIP_LABEL_DECL
  CP '.'
  JR NZ,EXECUTE_COMMAND_CLASSIFY
  INC HL
  LD A,(HL)
  OR A
  RET Z
  DEC HL

EXECUTE_COMMAND_CLASSIFY:
  CALL CLASSIFY_COMMAND
  OR A
  JR NZ,EXECUTE_DISPATCH

  ; キーワードで始まらない場合は暗黙 LET を試みる。
  CALL TRY_IMPLICIT_ASSIGNMENT
  RET

EXECUTE_SKIP_LABEL_DECL:
  INC HL
EXECUTE_SKIP_LABEL_DECL_LOOP:
  LD A,(HL)
  OR A
  RET Z
  CP ':'
  JR Z,EXECUTE_SKIP_LABEL_DECL_DONE
  INC HL
  JR EXECUTE_SKIP_LABEL_DECL_LOOP
EXECUTE_SKIP_LABEL_DECL_DONE:
  INC HL
  CALL SKIP_SPACES
  CALL SET_CMDPTR_FROM_HL
  LD A,(HL)
  OR A
  RET Z
  JR EXECUTE_COMMAND_CLASSIFY

EXECUTE_TRY_ABNORMAL_TAIL:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  CP '?'
  JR NZ,EXECUTE_TRY_ABNORMAL_NO
  INC HL
  LD A,(HL)
  CP '?'
  JR NZ,EXECUTE_TRY_ABNORMAL_NO
  INC HL
  LD A,(HL)
  CP '?'
  JR NZ,EXECUTE_TRY_ABNORMAL_NO
  INC HL
  CALL SKIP_SPACES
  LD A,(HL)
  OR A
  JR NZ,EXECUTE_TRY_ABNORMAL_NO
  SCF
  RET
EXECUTE_TRY_ABNORMAL_NO:
  AND A
  RET

EXECUTE_DISPATCH:
  PUSH AF
  CALL EXECUTE_TRY_ABNORMAL_TAIL
  JR NC,EXECUTE_DISPATCH_NORMAL
  POP AF
  RET
EXECUTE_DISPATCH_NORMAL:
  POP AF
  CP CMD_NEW
  JP Z,EXEC_CMD_NEW
  CP CMD_LIST
  JP Z,EXEC_CMD_LIST
  CP CMD_RUN
  JP Z,EXEC_CMD_RUN
  CP CMD_PRINT
  JP Z,EXEC_CMD_PRINT
  CP CMD_LET
  JP Z,EXEC_CMD_LET
  CP CMD_INPUT
  JP Z,EXEC_CMD_INPUT
  CP CMD_GOTO
  JP Z,EXEC_CMD_GOTO
  CP CMD_GOSUB
  JP Z,EXEC_CMD_GOSUB
  CP CMD_RETURN
  JP Z,EXEC_CMD_RETURN
  CP CMD_END
  JP Z,EXEC_CMD_END
  CP CMD_STOP
  JP Z,EXEC_CMD_STOP
  CP CMD_CONT
  JP Z,EXEC_CMD_CONT
  CP CMD_IF
  JP Z,EXEC_CMD_IF
  CP CMD_CLS
  JP Z,CMD_CLS_HANDLER
  CP CMD_REM
  RET Z
  CP CMD_FOR
  JP Z,EXEC_CMD_FOR
  CP CMD_NEXT
  JP Z,EXEC_CMD_NEXT
  CP CMD_DIM
  JP Z,EXEC_CMD_DIM
  CP CMD_DATA
  JP Z,EXEC_CMD_DATA
  CP CMD_READ
  JP Z,EXEC_CMD_READ
  CP CMD_RESTORE
  JP Z,EXEC_CMD_RESTORE
  CP CMD_POKE
  JP Z,CMD_POKE_HANDLER
  CP CMD_OUT
  JP Z,CMD_OUT_HANDLER
  CP CMD_BEEP
  JP Z,CMD_BEEP_HANDLER
  CP CMD_WAIT
  JP Z,CMD_WAIT_HANDLER
  CP CMD_LOCATE
  JP Z,CMD_LOCATE_HANDLER
  CP CMD_AUTO
  JP Z,CMD_AUTO_HANDLER
  CP CMD_BLOAD
  JP Z,CMD_BLOAD_HANDLER
  CP CMD_BSAVE
  JP Z,CMD_BSAVE_HANDLER
  CP CMD_FILES
  JP Z,CMD_FILES_HANDLER
  CP CMD_HDCOPY
  JP Z,CMD_HDCOPY_HANDLER
  CP CMD_PAINT
  JP Z,CMD_PAINT_HANDLER
  CP CMD_CIRCLE
  JP Z,CMD_CIRCLE_HANDLER
  CP CMD_PASS
  JP Z,EXEC_CMD_PASS
  CP CMD_PIOSET
  JP Z,EXEC_CMD_PIOSET
  CP CMD_PIOPUT
  JP Z,EXEC_CMD_PIOPUT
  CP CMD_SPOUT
  JP Z,EXEC_CMD_SPOUT
  CP CMD_SPINP
  JP Z,EXEC_CMD_SPINP
  CP CMD_REPEAT
  JP Z,EXEC_CMD_REPEAT
  CP CMD_UNTIL
  JP Z,EXEC_CMD_UNTIL
  CP CMD_WHILE
  JP Z,EXEC_CMD_WHILE
  CP CMD_WEND
  JP Z,EXEC_CMD_WEND
  CP CMD_LNINPUT
  JP Z,EXEC_CMD_LNINPUT
  CP CMD_CLEAR
  JP Z,EXEC_CMD_CLEAR
  CP CMD_DELETE
  JP Z,EXEC_CMD_DELETE
  CP CMD_ERASE
  JP Z,EXEC_CMD_ERASE
  CP CMD_ON
  JP Z,EXEC_CMD_ON
  CP CMD_RANDOMIZE
  JP Z,EXEC_CMD_RANDOMIZE
  CP CMD_RENUM
  JP Z,EXEC_CMD_RENUM
  CP CMD_USING
  JP Z,EXEC_CMD_USING
  CP CMD_MON
  JP Z,EXEC_CMD_MON
  CP CMD_OPEN
  JP Z,CMD_OPEN_HANDLER
  CP CMD_CLOSE
  JP Z,CMD_CLOSE_HANDLER
  CP CMD_LOAD
  JP Z,CMD_LOAD_HANDLER
  CP CMD_SAVE
  JP Z,CMD_SAVE_HANDLER
  CP CMD_LFILES
  JP Z,CMD_LFILES_HANDLER
  CP CMD_LCOPY
  JP Z,CMD_LCOPY_HANDLER
  CP CMD_KILL
  JP Z,CMD_KILL_HANDLER
  CP CMD_CALL
  JP Z,EXEC_CMD_CALL
  CP CMD_GCURSOR
  JP Z,CMD_GCURSOR_HANDLER
  CP CMD_GPRINT
  JP Z,CMD_GPRINT_HANDLER
  CP CMD_LINE
  JP Z,CMD_LINE_HANDLER
  CP CMD_PSET
  JP Z,CMD_PSET_HANDLER
  CP CMD_PRESET
  JP Z,CMD_PRESET_HANDLER
  CP CMD_LLIST
  JP Z,EXEC_CMD_LLIST
  CP CMD_LPRINT
  JP Z,EXEC_CMD_LPRINT
  CP CMD_DEGREE
  JP Z,EXEC_CMD_DEGREE
  CP CMD_RADIAN
  JP Z,EXEC_CMD_RADIAN
  CP CMD_GRAD
  JP Z,EXEC_CMD_GRAD
  CP CMD_TRON
  JP Z,EXEC_CMD_TRON
  CP CMD_TROFF
  JP Z,EXEC_CMD_TROFF
  CP CMD_ELSE
  JP Z,EXEC_CMD_ELSE
  CP CMD_EMPTY
  RET Z
  RET

; ----------------------------------------------------------------------------
; ルーチン: TRY_IMPLICIT_ASSIGNMENT
; 役割: キーワード不一致時に "A=1" 形式の代入を試行する。
; ----------------------------------------------------------------------------
TRY_IMPLICIT_ASSIGNMENT:
  CALL GET_CMDPTR_HL
  CALL EXPR_SET_PTR_HL
  JP EXEC_ASSIGNMENT_FROM_EXPRPTR

; ----------------------------------------------------------------------------
; 命令: NEW
; ----------------------------------------------------------------------------
EXEC_CMD_NEW:
  CALL ASSERT_END_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL CLEAR_PROGRAM
  CALL CLEAR_VARIABLE_TABLE
  RET

; ----------------------------------------------------------------------------
; 命令: LIST
; ----------------------------------------------------------------------------
EXEC_CMD_LIST:
  CALL ASSERT_END_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL LIST_PROGRAM
  RET

; ----------------------------------------------------------------------------
; 命令: RUN
; ----------------------------------------------------------------------------
EXEC_CMD_RUN:
  CALL ASSERT_END_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  LD A,0x80
  OUT (LCD_CMD_PORT),A
  XOR A
  LD (RAM_TEXT_COL),A
  CALL RUN_STORED_PROGRAM
  RET

; ----------------------------------------------------------------------------
; 命令: PRINT
; ----------------------------------------------------------------------------
EXEC_CMD_PRINT:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  XOR A
  LD (RAM_DATA_SCAN_LO),A  ; PRINT内の列位置
  LD (RAM_DATA_SCAN_HI),A  ; PRINT内の項目数

  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  OR A
  JP Z,PRINT_CRLF
  LD DE,TOKEN_USING
  CALL MATCH_TOKEN
  JP C,PRINT_USING_MODE

PRINT_ITEM_LOOP:
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ';'
  JP Z,SET_SYNTAX_ERROR
  CP ','
  JP Z,SET_SYNTAX_ERROR
  CP '"'
  JR Z,PRINT_QUOTED

  CALL PRINT_TRY_CHAR_FUNCTION
  JR NC,PRINT_EVAL_NUMBER
  ; CHAR$/CHR$ は1文字出力
  LD A,(RAM_DATA_SCAN_LO)
  INC A
  LD (RAM_DATA_SCAN_LO),A
  LD A,(RAM_DATA_SCAN_HI)
  INC A
  LD (RAM_DATA_SCAN_HI),A
  JR PRINT_DELIM

PRINT_EVAL_NUMBER:
  CALL EVAL_EXPRESSION
  PUSH HL
  CALL PRINT_NUMBER_LEN_HL
  LD B,A
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  LD C,A
  POP HL

  ; 項目が1つの式の場合は12桁内で右詰め。
  LD A,(RAM_DATA_SCAN_HI)
  OR A
  JR NZ,PRINT_NUMBER_DO_OUTPUT
  LD A,C
  OR A
  JR Z,PRINT_NUMBER_ALIGN_FIELD
  CP ';'
  JR NZ,PRINT_NUMBER_DO_OUTPUT
  PUSH BC
  PUSH HL
  INC HL
  CALL SKIP_SPACES
  LD A,(HL)
  POP HL
  POP BC
  OR A
  JR NZ,PRINT_NUMBER_DO_OUTPUT

PRINT_NUMBER_ALIGN_FIELD:
  LD A,(RAM_TEXT_COL)
  LD C,A
  LD A,24
  SUB C
  SUB B
  JR C,PRINT_NUMBER_DO_OUTPUT
  JR Z,PRINT_NUMBER_DO_OUTPUT
  LD B,A
  CALL PRINT_SPACES_COUNT_B

PRINT_NUMBER_DO_OUTPUT:
  PUSH BC
  CALL PRINT_NUMBER_HL
  POP BC
  LD A,(RAM_DATA_SCAN_LO)
  ADD A,B
  LD (RAM_DATA_SCAN_LO),A
  LD A,(RAM_DATA_SCAN_HI)
  INC A
  LD (RAM_DATA_SCAN_HI),A
  JR PRINT_DELIM

PRINT_QUOTED:
  INC HL
PRINT_QUOTED_LOOP:
  LD A,(HL)
  OR A
  JR Z,PRINT_DELIM_END
  CP '"'
  JR Z,PRINT_QUOTED_DONE
  CALL OUT_LCD_CHAR
  LD A,(RAM_DATA_SCAN_LO)
  INC A
  LD (RAM_DATA_SCAN_LO),A
  INC HL
  JR PRINT_QUOTED_LOOP

PRINT_QUOTED_DONE:
  INC HL
  LD A,(RAM_DATA_SCAN_HI)
  INC A
  LD (RAM_DATA_SCAN_HI),A
PRINT_DELIM_END:
  CALL EXPR_SET_PTR_HL

PRINT_DELIM:
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  OR A
  JP Z,PRINT_ENDLINE_IF_NEEDED
  CP ';'
  JR Z,PRINT_DELIM_SEMI
  CP ','
  JR Z,PRINT_DELIM_COMMA
  JP PRINT_CRLF

PRINT_DELIM_SEMI:
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  OR A
  RET Z
  JP PRINT_ITEM_LOOP

PRINT_DELIM_COMMA:
  CALL PRINT_TAB_TO_NEXT_12
  INC HL
  CALL EXPR_SET_PTR_HL
  JP PRINT_ITEM_LOOP

PRINT_ENDLINE_IF_NEEDED:
  LD A,(RAM_DATA_SCAN_HI)
  OR A
  JP Z,PRINT_CRLF
  LD A,(RAM_TEXT_COL)
  OR A
  RET Z
  JP PRINT_CRLF

PRINT_USING_MODE:
  CALL EXPR_SET_PTR_HL
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP '"'
  JP NZ,SET_SYNTAX_ERROR
PRINT_USING_SKIP_FMT:
  INC HL
  LD A,(HL)
  OR A
  JP Z,SET_SYNTAX_ERROR
  CP '"'
  JR NZ,PRINT_USING_SKIP_FMT
  INC HL
  LD A,(HL)
  CP ';'
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL PRINT_NUMBER_HL
  JP PRINT_CRLF

; ----------------------------------------------------------------------------
; ルーチン: PRINT_TRY_CHAR_FUNCTION
; 役割: PRINT項目先頭の CHR$(...) / CHAR$(...) を文字出力として処理する。
; 出力: Carry=1 処理済み, Carry=0 非該当
; ----------------------------------------------------------------------------
PRINT_TRY_CHAR_FUNCTION:
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL

  ; C...
  LD A,(HL)
  CALL TO_UPPER
  CP 'C'
  JR NZ,PRINT_TRY_CHAR_NONE
  INC HL
  ; CH...
  LD A,(HL)
  CALL TO_UPPER
  CP 'H'
  JR NZ,PRINT_TRY_CHAR_NONE
  INC HL
  ; CHR$ or CHAR$
  LD A,(HL)
  CALL TO_UPPER
  CP 'A'
  JR Z,PRINT_TRY_CHAR_CHAR_PATH
  CP 'R'
  JR NZ,PRINT_TRY_CHAR_NONE
  INC HL
  LD A,(HL)
  CP '$'
  JR NZ,PRINT_TRY_CHAR_NONE
  JR PRINT_TRY_CHAR_PARSE_ARGS

PRINT_TRY_CHAR_CHAR_PATH:
  INC HL
  LD A,(HL)
  CALL TO_UPPER
  CP 'R'
  JR NZ,PRINT_TRY_CHAR_NONE
  INC HL
  LD A,(HL)
  CP '$'
  JR NZ,PRINT_TRY_CHAR_NONE

PRINT_TRY_CHAR_PARSE_ARGS:
  INC HL
  CALL SKIP_SPACES
  LD A,(HL)
  CP '('
  JR Z,PRINT_TRY_CHAR_HAVE_PAREN
  CALL SET_SYNTAX_ERROR
  SCF
  RET

PRINT_TRY_CHAR_HAVE_PAREN:
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  PUSH HL
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ')'
  JR Z,PRINT_TRY_CHAR_CLOSE_OK
  POP HL
  CALL SET_SYNTAX_ERROR
  SCF
  RET

PRINT_TRY_CHAR_CLOSE_OK:
  INC HL
  CALL EXPR_SET_PTR_HL
  POP HL
  LD A,L
  CALL OUT_LCD_CHAR
  SCF
  RET

PRINT_TRY_CHAR_NONE:
  AND A
  RET

; ----------------------------------------------------------------------------
; ルーチン: PRINT_NUMBER_LEN_HL
; 役割: HL を10進表示したときの文字数を A に返す（符号込み）
; ----------------------------------------------------------------------------
PRINT_NUMBER_LEN_HL:
  PUSH BC
  PUSH DE
  PUSH HL
  LD B,0
  LD A,H
  AND 0x80
  JR Z,PRINT_NUMBER_LEN_POSITIVE
  INC B
  LD A,H
  CPL
  LD H,A
  LD A,L
  CPL
  LD L,A
  INC HL
PRINT_NUMBER_LEN_POSITIVE:
  LD A,H
  OR L
  JR NZ,PRINT_NUMBER_LEN_NONZERO
  INC B
  LD A,B
  POP HL
  POP DE
  POP BC
  RET
PRINT_NUMBER_LEN_NONZERO:
PRINT_NUMBER_LEN_LOOP:
  CALL DIV10_HL
  INC B
  LD A,H
  OR L
  JR NZ,PRINT_NUMBER_LEN_LOOP
  LD A,B
  POP HL
  POP DE
  POP BC
  RET

; ----------------------------------------------------------------------------
; ルーチン: PRINT_TAB_TO_NEXT_12
; 役割: 現在列から次の12桁境界まで空白を出力する。
; ----------------------------------------------------------------------------
PRINT_TAB_TO_NEXT_12:
  LD A,(RAM_DATA_SCAN_LO)
  LD B,12
PRINT_TAB_REDUCE:
  CP 12
  JR C,PRINT_TAB_HAVE_REMAINDER
  SUB 12
  JR PRINT_TAB_REDUCE
PRINT_TAB_HAVE_REMAINDER:
  LD C,A
  LD A,12
  SUB C
  LD B,A
  JR NZ,PRINT_TAB_HAVE_SPACES
  LD B,12
PRINT_TAB_HAVE_SPACES:
  CALL PRINT_SPACES_COUNT_B
  RET

; ----------------------------------------------------------------------------
; ルーチン: PRINT_SPACES_COUNT_B
; 役割: B個の空白を出力し、列位置を進める。
; ----------------------------------------------------------------------------
PRINT_SPACES_COUNT_B:
  LD A,B
  OR A
  RET Z
PRINT_SPACES_COUNT_B_LOOP:
  CALL PRINT_SPACE
  LD A,(RAM_DATA_SCAN_LO)
  INC A
  LD (RAM_DATA_SCAN_LO),A
  DJNZ PRINT_SPACES_COUNT_B_LOOP
  RET

; ----------------------------------------------------------------------------
; 命令: LET / 暗黙 LET
; ----------------------------------------------------------------------------
EXEC_CMD_LET:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL EXEC_ASSIGNMENT_FROM_EXPRPTR
  RET

EXEC_ASSIGNMENT_FROM_EXPRPTR:
  XOR A
  LD (RAM_CMP_OP),A
  CALL PARSE_VARIABLE_KEY_FROM_EXPR
  JP NC,SET_SYNTAX_ERROR
  LD A,(RAM_TMP_KEY1)
  LD (RAM_ASSIGN_KEY1),A
  LD A,(RAM_TMP_KEY2)
  LD (RAM_ASSIGN_KEY2),A
  LD A,(RAM_TMP_KEY3)
  LD (RAM_ASSIGN_KEY3),A
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP '('
  JR NZ,EXEC_ASSIGNMENT_EQ_CHECK
  LD A,1
  LD (RAM_CMP_OP),A
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD A,H
  OR A
  JP NZ,SET_SYNTAX_ERROR
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ')'
  RET NZ
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
EXEC_ASSIGNMENT_EQ_CHECK:
  LD A,(HL)
  CP '='
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD A,(RAM_CMP_OP)
  OR A
  JR Z,EXEC_ASSIGNMENT_STORE_EVAL
  LD DE,7
  JR EXEC_ASSIGNMENT_STORE
EXEC_ASSIGNMENT_STORE_EVAL:
  LD D,H
  LD E,L
EXEC_ASSIGNMENT_STORE:
  ; 右辺評価中に RAM_TMP_KEY* が参照変数で上書きされるため、
  ; 代入先キーを退避領域から復元してから書き込む。
  LD A,(RAM_ASSIGN_KEY1)
  LD (RAM_TMP_KEY1),A
  LD A,(RAM_ASSIGN_KEY2)
  LD (RAM_TMP_KEY2),A
  LD A,(RAM_ASSIGN_KEY3)
  LD (RAM_TMP_KEY3),A
  CALL SET_VARIABLE_FROM_DE
  RET

; ----------------------------------------------------------------------------
; 命令: INPUT / LNINPUT
; 役割: 簡易実装として対象変数へ 0 を格納する。
; ----------------------------------------------------------------------------
EXEC_CMD_INPUT:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL PARSE_VARIABLE_KEY_FROM_EXPR
  JP NC,SET_SYNTAX_ERROR
  CALL ASSERT_END_FROM_EXPRPTR
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL READ_LINE
  LD A,(RAM_FLAG_EOT)
  OR A
  JR NZ,EXEC_CMD_INPUT_ZERO
  LD HL,RAM_LINEBUF
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD D,H
  LD E,L
  CALL SET_VARIABLE_FROM_DE
  RET
EXEC_CMD_INPUT_ZERO:
  LD DE,0
  CALL SET_VARIABLE_FROM_DE
  RET

EXEC_CMD_LNINPUT:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL PARSE_VARIABLE_KEY_FROM_EXPR
  JP NC,SET_SYNTAX_ERROR
  CALL ASSERT_END_FROM_EXPRPTR
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL READ_LINE
  LD A,(RAM_FLAG_EOT)
  OR A
  RET NZ
  LD HL,RAM_LINEBUF
EXEC_CMD_LNINPUT_ECHO:
  LD A,(HL)
  OR A
  JR Z,EXEC_CMD_LNINPUT_DONE
  CALL OUT_LCD_CHAR
  INC HL
  JR EXEC_CMD_LNINPUT_ECHO
EXEC_CMD_LNINPUT_DONE:
  CALL PRINT_CRLF
  RET

; ----------------------------------------------------------------------------
; 命令: GOTO
; ----------------------------------------------------------------------------
EXEC_CMD_GOTO:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  CP '*'
  JR NZ,EXEC_CMD_GOTO_LINE_NUMBER
  CALL EXPR_SET_PTR_HL
  CALL PARSE_LABEL_REF_FROM_EXPRPTR
  JP NC,SET_SYNTAX_ERROR
  CALL ASSERT_END_FROM_EXPRPTR
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL FIND_LABEL_PTR_BY_KEY
  JP NC,SET_SYNTAX_ERROR
  LD A,C
  LD (RAM_OVERRIDE_LO),A
  LD A,B
  LD (RAM_OVERRIDE_HI),A
  LD A,1
  LD (RAM_PTR_OVERRIDE),A
  RET

EXEC_CMD_GOTO_LINE_NUMBER:
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD A,L
  LD (RAM_JUMP_LINE_LO),A
  LD A,H
  LD (RAM_JUMP_LINE_HI),A
  LD A,1
  LD (RAM_JUMP_FLAG),A
  ; RUNAWAY 抑止: 現在行への自己 GOTO はエラー扱いにする。
  LD HL,RAM_LINEBUF
  CALL SKIP_SPACES
  CALL PARSE_LINE_NUMBER_FROM_HL
  JR NC,EXEC_CMD_GOTO_DONE
  LD A,(RAM_JUMP_LINE_LO)
  CP E
  JR NZ,EXEC_CMD_GOTO_DONE
  LD A,(RAM_JUMP_LINE_HI)
  CP D
  JR NZ,EXEC_CMD_GOTO_DONE
  LD A,7
  LD (RAM_LAST_ERROR),A
EXEC_CMD_GOTO_DONE:
  RET

; ----------------------------------------------------------------------------
; 命令: GOSUB
; ----------------------------------------------------------------------------
EXEC_CMD_GOSUB:
  LD A,(RAM_GOSUB_SP)
  CP GOSUB_MAX_DEPTH
  RET NC

  ; 返り先(次レコード)をスタックへ積む
  LD E,A
  ADD A,A
  LD E,A
  LD D,0
  LD HL,RAM_GOSUB_STACK
  ADD HL,DE
  LD A,(RAM_NEXT_PTR_LO)
  LD (HL),A
  INC HL
  LD A,(RAM_NEXT_PTR_HI)
  LD (HL),A

  LD A,(RAM_GOSUB_SP)
  INC A
  LD (RAM_GOSUB_SP),A

  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  CP '*'
  JP NZ,EXEC_CMD_GOTO
  CALL EXPR_SET_PTR_HL
  CALL PARSE_LABEL_REF_FROM_EXPRPTR
  JP NC,SET_SYNTAX_ERROR
  CALL ASSERT_END_FROM_EXPRPTR
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL FIND_LABEL_PTR_BY_KEY
  JP NC,SET_SYNTAX_ERROR
  LD A,C
  LD (RAM_OVERRIDE_LO),A
  LD A,B
  LD (RAM_OVERRIDE_HI),A
  LD A,1
  LD (RAM_PTR_OVERRIDE),A
  RET

; ----------------------------------------------------------------------------
; 命令: RETURN
; ----------------------------------------------------------------------------
EXEC_CMD_RETURN:
  LD A,(RAM_GOSUB_SP)
  OR A
  JP Z,SET_SYNTAX_ERROR
  DEC A
  LD (RAM_GOSUB_SP),A

  LD E,A
  ADD A,A
  LD E,A
  LD D,0
  LD HL,RAM_GOSUB_STACK
  ADD HL,DE
  LD A,(HL)
  LD (RAM_OVERRIDE_LO),A
  INC HL
  LD A,(HL)
  LD (RAM_OVERRIDE_HI),A
  LD A,1
  LD (RAM_PTR_OVERRIDE),A
  RET

; ----------------------------------------------------------------------------
; 命令: END / STOP
; ----------------------------------------------------------------------------
EXEC_CMD_END:
  CALL ASSERT_END_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  LD A,1
  LD (RAM_EXEC_STOP),A
  RET

EXEC_CMD_STOP:
  CALL ASSERT_END_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  LD A,(RAM_NEXT_PTR_LO)
  LD (RAM_PAUSE_PTR_LO),A
  LD A,(RAM_NEXT_PTR_HI)
  LD (RAM_PAUSE_PTR_HI),A
  LD A,1
  LD (RAM_PAUSE_FLAG),A
  JP EXEC_CMD_END

EXEC_CMD_CONT:
  CALL ASSERT_END_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  LD A,(RAM_PAUSE_FLAG)
  OR A
  RET Z
  XOR A
  LD (RAM_PAUSE_FLAG),A
  LD (RAM_EXEC_STOP),A
  LD (RAM_PTR_OVERRIDE),A
  LD A,(RAM_PAUSE_PTR_LO)
  LD (RAM_RUN_PTR_LO),A
  LD A,(RAM_PAUSE_PTR_HI)
  LD (RAM_RUN_PTR_HI),A
  JP RUN_PROGRAM_MAIN_LOOP

; ----------------------------------------------------------------------------
; 命令: IF
; 形式: IF <expr><cmp><expr> THEN <line|statement>
; ----------------------------------------------------------------------------
EXEC_CMD_IF:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  PUSH HL

  CALL PARSE_COMPARATOR_FROM_EXPRPTR
  JR C,EXEC_CMD_IF_HAVE_CMP
  POP HL
  JP SET_SYNTAX_ERROR

EXEC_CMD_IF_HAVE_CMP:
  LD (RAM_CMP_OP),A
  CALL EVAL_EXPRESSION
  POP DE
  LD B,D
  LD C,E
  LD D,H
  LD E,L
  CALL CMP_BC_DE_UNSIGNED
  LD (RAM_TMP_VAL_LO),A

  LD A,(RAM_CMP_OP)
  CP CMP_EQ
  JR Z,IF_CHECK_EQ
  CP CMP_NE
  JR Z,IF_CHECK_NE
  CP CMP_LT
  JR Z,IF_CHECK_LT
  CP CMP_GT
  JR Z,IF_CHECK_GT
  CP CMP_LE
  JR Z,IF_CHECK_LE
  CP CMP_GE
  JR Z,IF_CHECK_GE
  RET

IF_CHECK_EQ:
  LD A,(RAM_TMP_VAL_LO)
  OR A
  JP Z,IF_THEN_EXEC
  JP IF_FIND_ELSE
IF_CHECK_NE:
  LD A,(RAM_TMP_VAL_LO)
  OR A
  JP NZ,IF_THEN_EXEC
  JP IF_FIND_ELSE
IF_CHECK_LT:
  LD A,(RAM_TMP_VAL_LO)
  CP 1
  JP Z,IF_THEN_EXEC
  JP IF_FIND_ELSE
IF_CHECK_GT:
  LD A,(RAM_TMP_VAL_LO)
  CP 2
  JP Z,IF_THEN_EXEC
  JP IF_FIND_ELSE
IF_CHECK_LE:
  LD A,(RAM_TMP_VAL_LO)
  CP 2
  JP NZ,IF_THEN_EXEC
  JP IF_FIND_ELSE
IF_CHECK_GE:
  LD A,(RAM_TMP_VAL_LO)
  CP 1
  JP NZ,IF_THEN_EXEC
  JP IF_FIND_ELSE

; ----------------------------------------------------------------------------
; ルーチン: CMP_BC_DE_UNSIGNED
; 役割: BC(lhs) と DE(rhs) を符号なし比較する。
; 出力: A=0(lhs==rhs), A=1(lhs<rhs), A=2(lhs>rhs)
; ----------------------------------------------------------------------------
CMP_BC_DE_UNSIGNED:
  LD A,B
  CP D
  JR C,CMP_BC_DE_LT
  JR NZ,CMP_BC_DE_GT
  LD A,C
  CP E
  JR C,CMP_BC_DE_LT
  JR NZ,CMP_BC_DE_GT
  XOR A
  RET
CMP_BC_DE_LT:
  LD A,1
  RET
CMP_BC_DE_GT:
  LD A,2
  RET

; ----------------------------------------------------------------------------
; ルーチン: PARSE_LABEL_KEY_FROM_HL
; 役割: HL位置からラベル名(先頭3文字)を抽出する。
; 出力: Carry=1 成功 / Carry=0 失敗, HL=ラベル末尾位置
; ----------------------------------------------------------------------------
PARSE_LABEL_KEY_FROM_HL:
  XOR A
  LD (RAM_TMP_KEY1),A
  LD (RAM_TMP_KEY2),A
  LD (RAM_TMP_KEY3),A
  LD B,0
PARSE_LABEL_KEY_LOOP:
  LD A,(HL)
  CALL TO_UPPER
  CALL IS_ALNUM
  JR C,PARSE_LABEL_KEY_ACCEPT
  CP '_'
  JR Z,PARSE_LABEL_KEY_ACCEPT
  JR PARSE_LABEL_KEY_DONE
PARSE_LABEL_KEY_ACCEPT:
  LD A,B
  CP 0
  JR NZ,PARSE_LABEL_KEY_SECOND
  LD A,(HL)
  CALL TO_UPPER
  LD (RAM_TMP_KEY1),A
  JR PARSE_LABEL_KEY_NEXT
PARSE_LABEL_KEY_SECOND:
  CP 1
  JR NZ,PARSE_LABEL_KEY_THIRD
  LD A,(HL)
  CALL TO_UPPER
  LD (RAM_TMP_KEY2),A
  JR PARSE_LABEL_KEY_NEXT
PARSE_LABEL_KEY_THIRD:
  CP 2
  JR NZ,PARSE_LABEL_KEY_NEXT
  LD A,(HL)
  CALL TO_UPPER
  LD (RAM_TMP_KEY3),A
PARSE_LABEL_KEY_NEXT:
  INC HL
  INC B
  JR PARSE_LABEL_KEY_LOOP
PARSE_LABEL_KEY_DONE:
  LD A,B
  OR A
  JR Z,PARSE_LABEL_KEY_FAIL
  SCF
  RET
PARSE_LABEL_KEY_FAIL:
  AND A
  RET

; ----------------------------------------------------------------------------
; ルーチン: PARSE_LABEL_REF_FROM_EXPRPTR
; 役割: 式ポインタ位置の *LABEL 参照を RAM_TMP_KEY* へ抽出する。
; ----------------------------------------------------------------------------
PARSE_LABEL_REF_FROM_EXPRPTR:
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP '*'
  JR NZ,PARSE_LABEL_REF_FAIL
  INC HL
  CALL PARSE_LABEL_KEY_FROM_HL
  JR NC,PARSE_LABEL_REF_FAIL
  CALL EXPR_SET_PTR_HL
  SCF
  RET
PARSE_LABEL_REF_FAIL:
  AND A
  RET

; ----------------------------------------------------------------------------
; ルーチン: FIND_LABEL_PTR_BY_KEY
; 役割: RAM_TMP_KEY* のラベル宣言行ポインタを BC へ返す（1件キャッシュ付）
; ----------------------------------------------------------------------------
FIND_LABEL_PTR_BY_KEY:
  LD A,(RAM_LABEL_CACHE_VALID)
  OR A
  JR Z,FIND_LABEL_SCAN_START
  LD A,(RAM_LABEL_CACHE_KEY1)
  LD D,A
  LD A,(RAM_TMP_KEY1)
  CP D
  JR NZ,FIND_LABEL_SCAN_START
  LD A,(RAM_LABEL_CACHE_KEY2)
  LD D,A
  LD A,(RAM_TMP_KEY2)
  CP D
  JR NZ,FIND_LABEL_SCAN_START
  LD A,(RAM_LABEL_CACHE_KEY3)
  LD D,A
  LD A,(RAM_TMP_KEY3)
  CP D
  JR NZ,FIND_LABEL_SCAN_START
  LD A,(RAM_LABEL_CACHE_PTR_LO)
  LD C,A
  LD A,(RAM_LABEL_CACHE_PTR_HI)
  LD B,A
  SCF
  RET

FIND_LABEL_SCAN_START:
  LD A,(RAM_TMP_KEY1)
  LD (RAM_ASSIGN_KEY1),A
  LD A,(RAM_TMP_KEY2)
  LD (RAM_ASSIGN_KEY2),A
  LD A,(RAM_TMP_KEY3)
  LD (RAM_ASSIGN_KEY3),A
  LD BC,RAM_PROG_START

FIND_LABEL_SCAN_LOOP:
  LD A,(RAM_PROG_PTR_LO)
  CP C
  JR NZ,FIND_LABEL_SCAN_HAS_RECORD
  LD A,(RAM_PROG_PTR_HI)
  CP B
  JR Z,FIND_LABEL_SCAN_NOT_FOUND

FIND_LABEL_SCAN_HAS_RECORD:
  PUSH BC
  LD H,B
  LD L,C
  INC HL
  CALL SKIP_SPACES
  CALL PARSE_LINE_NUMBER_FROM_HL
  JR NC,FIND_LABEL_SCAN_NO_LINE_NUMBER
  CALL SKIP_SPACES
FIND_LABEL_SCAN_NO_LINE_NUMBER:
  LD A,(HL)
  CP '*'
  JR NZ,FIND_LABEL_SCAN_NEXT_RECORD
  INC HL
  CALL PARSE_LABEL_KEY_FROM_HL
  JR NC,FIND_LABEL_SCAN_NEXT_RECORD
  LD A,(HL)
  CP ':'
  JR NZ,FIND_LABEL_SCAN_NEXT_RECORD

  LD A,(RAM_ASSIGN_KEY1)
  LD D,A
  LD A,(RAM_TMP_KEY1)
  CP D
  JR NZ,FIND_LABEL_SCAN_NEXT_RECORD
  LD A,(RAM_ASSIGN_KEY2)
  LD D,A
  LD A,(RAM_TMP_KEY2)
  CP D
  JR NZ,FIND_LABEL_SCAN_NEXT_RECORD
  LD A,(RAM_ASSIGN_KEY3)
  LD D,A
  LD A,(RAM_TMP_KEY3)
  CP D
  JR NZ,FIND_LABEL_SCAN_NEXT_RECORD

  POP BC
  LD A,1
  LD (RAM_LABEL_CACHE_VALID),A
  LD A,(RAM_ASSIGN_KEY1)
  LD (RAM_LABEL_CACHE_KEY1),A
  LD A,(RAM_ASSIGN_KEY2)
  LD (RAM_LABEL_CACHE_KEY2),A
  LD A,(RAM_ASSIGN_KEY3)
  LD (RAM_LABEL_CACHE_KEY3),A
  LD A,C
  LD (RAM_LABEL_CACHE_PTR_LO),A
  LD A,B
  LD (RAM_LABEL_CACHE_PTR_HI),A
  SCF
  RET

FIND_LABEL_SCAN_NEXT_RECORD:
  POP BC
  LD A,(BC)
  LD E,A
  INC BC
  LD D,0
  PUSH HL
  LD H,B
  LD L,C
  ADD HL,DE
  LD B,H
  LD C,L
  POP HL
  JR FIND_LABEL_SCAN_LOOP

FIND_LABEL_SCAN_NOT_FOUND:
  AND A
  RET

IF_FIND_ELSE:
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
IF_FIND_ELSE_LOOP:
  LD A,(HL)
  OR A
  RET Z
  CALL TO_UPPER
  CP 'E'
  JR NZ,IF_FIND_ELSE_NEXT
  INC HL
  LD A,(HL)
  CALL TO_UPPER
  CP 'L'
  JR NZ,IF_FIND_ELSE_BACK1
  INC HL
  LD A,(HL)
  CALL TO_UPPER
  CP 'S'
  JR NZ,IF_FIND_ELSE_BACK2
  INC HL
  LD A,(HL)
  CALL TO_UPPER
  CP 'E'
  JR NZ,IF_FIND_ELSE_BACK3
  INC HL
  CALL SET_CMDPTR_FROM_HL
  CALL EXECUTE_COMMAND_AT_CMDPTR
  RET
IF_FIND_ELSE_BACK3:
  DEC HL
IF_FIND_ELSE_BACK2:
  DEC HL
IF_FIND_ELSE_BACK1:
  DEC HL
IF_FIND_ELSE_NEXT:
  INC HL
  JR IF_FIND_ELSE_LOOP

IF_THEN_EXEC:
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD DE,TOKEN_THEN
  CALL MATCH_TOKEN
  JR C,IF_THEN_EXEC_HAVE_THEN
  ; THEN は省略可能（PC-G815仕様）
  CALL EXPR_SET_PTR_HL
  JR IF_THEN_EXEC_BODY
IF_THEN_EXEC_HAVE_THEN:
  CALL EXPR_SET_PTR_HL
IF_THEN_EXEC_BODY:
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP '*'
  JR Z,IF_THEN_LABEL_JUMP
  CALL IS_DIGIT
  JR NC,IF_THEN_STATEMENT

  CALL PARSE_LINE_NUMBER_FROM_HL
  RET NC
  LD A,E
  LD (RAM_JUMP_LINE_LO),A
  LD A,D
  LD (RAM_JUMP_LINE_HI),A
  LD A,1
  LD (RAM_JUMP_FLAG),A
  RET

IF_THEN_LABEL_JUMP:
  CALL EXPR_SET_PTR_HL
  CALL PARSE_LABEL_REF_FROM_EXPRPTR
  RET NC
  CALL ASSERT_END_FROM_EXPRPTR
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL FIND_LABEL_PTR_BY_KEY
  RET NC
  LD A,C
  LD (RAM_OVERRIDE_LO),A
  LD A,B
  LD (RAM_OVERRIDE_HI),A
  LD A,1
  LD (RAM_PTR_OVERRIDE),A
  RET

IF_THEN_STATEMENT:
  CALL SET_CMDPTR_FROM_HL
  CALL EXECUTE_COMMAND_AT_CMDPTR
  RET

; ----------------------------------------------------------------------------
; 命令: FOR
; 形式: FOR <var>=<expr> TO <expr> [STEP <expr>]
; ----------------------------------------------------------------------------
EXEC_CMD_FOR:
  LD A,(RAM_FOR_SP)
  CP FOR_MAX_DEPTH
  JP NC,SET_SYNTAX_ERROR

  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL PARSE_VARIABLE_KEY_FROM_EXPR
  JP NC,SET_SYNTAX_ERROR

  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP '='
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD D,H
  LD E,L
  CALL SET_VARIABLE_FROM_DE

  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD DE,TOKEN_TO
  CALL MATCH_TOKEN
  JP NC,SET_SYNTAX_ERROR
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD A,L
  LD (RAM_TMP_VAL_LO),A
  LD A,H
  LD (RAM_TMP_VAL_HI),A

  LD DE,1
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  OR A
  JR Z,FOR_HAVE_STEP
  LD DE,TOKEN_STEP
  CALL MATCH_TOKEN
  JR NC,FOR_HAVE_STEP
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD D,H
  LD E,L

FOR_HAVE_STEP:
  ; フレーム先頭を HL に求める
  LD A,(RAM_FOR_SP)
  LD B,A
  LD HL,RAM_FOR_STACK
FOR_FRAME_ADDR_LOOP:
  LD A,B
  OR A
  JR Z,FOR_FRAME_ADDR_DONE
  LD DE,FOR_FRAME_SIZE
  ADD HL,DE
  DEC B
  JR FOR_FRAME_ADDR_LOOP
FOR_FRAME_ADDR_DONE:
  LD A,(RAM_TMP_KEY1)
  LD (HL),A
  INC HL
  LD A,(RAM_TMP_KEY2)
  LD (HL),A
  INC HL
  LD A,(RAM_TMP_KEY3)
  LD (HL),A
  INC HL
  LD A,(RAM_TMP_VAL_LO)
  LD (HL),A
  INC HL
  LD A,(RAM_TMP_VAL_HI)
  LD (HL),A
  INC HL
  LD A,E
  LD (HL),A
  INC HL
  LD A,D
  LD (HL),A
  INC HL
  LD A,(RAM_NEXT_PTR_LO)
  LD (HL),A
  INC HL
  LD A,(RAM_NEXT_PTR_HI)
  LD (HL),A

  LD A,(RAM_FOR_SP)
  INC A
  LD (RAM_FOR_SP),A
  RET

; ----------------------------------------------------------------------------
; 命令: NEXT
; 役割: 最上位 FOR フレームを更新して継続判定する。
; ----------------------------------------------------------------------------
EXEC_CMD_NEXT:
  LD A,(RAM_FOR_SP)
  OR A
  JP Z,SET_SYNTAX_ERROR
  DEC A
  LD B,A

  LD HL,RAM_FOR_STACK
NEXT_FRAME_ADDR_LOOP:
  LD A,B
  OR A
  JR Z,NEXT_FRAME_ADDR_DONE
  LD DE,FOR_FRAME_SIZE
  ADD HL,DE
  DEC B
  JR NEXT_FRAME_ADDR_LOOP
NEXT_FRAME_ADDR_DONE:
  ; key を RAM_TMP_KEY* へ
  LD A,(HL)
  LD (RAM_TMP_KEY1),A
  INC HL
  LD A,(HL)
  LD (RAM_TMP_KEY2),A
  INC HL
  LD A,(HL)
  LD (RAM_TMP_KEY3),A
  INC HL
  ; end をスタックへ退避
  LD E,(HL)   ; end lo
  INC HL
  LD D,(HL)   ; end hi
  PUSH DE
  INC HL
  ; step をスタックへ退避
  LD E,(HL)   ; step lo
  INC HL
  LD D,(HL)   ; step hi
  PUSH DE
  INC HL
  ; loop ptr
  LD A,(HL)
  LD (RAM_OVERRIDE_LO),A
  INC HL
  LD A,(HL)
  LD (RAM_OVERRIDE_HI),A

  ; step を取り出し、符号情報だけ AF で保持する
  POP BC              ; B=step hi, C=step lo
  LD A,B
  AND 0x80
  LD (RAM_CMP_OP),A

  ; new = cur + step
  PUSH BC
  CALL GET_VARIABLE_HL
  POP BC
  LD A,C
  ADD A,L
  LD E,A
  LD A,B
  ADC A,H
  LD D,A
  CALL SET_VARIABLE_FROM_DE

  ; compare: BC=new, DE=end
  LD B,D
  LD C,E
  POP DE              ; end
  CALL CMP_BC_DE_UNSIGNED
  LD B,A

  LD A,(RAM_CMP_OP)
  OR A
  JR NZ,NEXT_NEG_STEP
  ; 正方向: var <= end
  LD A,B
  CP 2
  JR NZ,NEXT_CONTINUE
  JR NEXT_POP_FRAME

NEXT_NEG_STEP:
  ; 負方向: var >= end
  LD A,B
  CP 1
  JR NZ,NEXT_CONTINUE
  JR NEXT_POP_FRAME

NEXT_CONTINUE:
  LD A,1
  LD (RAM_PTR_OVERRIDE),A
  RET

NEXT_POP_FRAME:
  LD A,(RAM_FOR_SP)
  DEC A
  LD (RAM_FOR_SP),A
  RET

; ----------------------------------------------------------------------------
; 命令: CLEAR
; ----------------------------------------------------------------------------
EXEC_CMD_CLEAR:
  CALL CLEAR_VARIABLE_TABLE
  CALL ASSERT_END_AFTER_CMD
  RET

EXEC_CMD_DIM:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL PARSE_VARIABLE_KEY_FROM_EXPR
  JP NC,SET_SYNTAX_ERROR
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP '('
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP '-'
  JP Z,SET_SYNTAX_ERROR
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ')'
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  JP ASSERT_END_FROM_HL

EXEC_CMD_DATA:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  XOR A
  LD (RAM_DATA_COUNT),A
  LD (RAM_DATA_INDEX),A
  LD A,(HL)
  CP '5'
  JR Z,EXEC_CMD_DATA_SET_56
  CP '9'
  JR Z,EXEC_CMD_DATA_SET_9
  CP '1'
  JR Z,EXEC_CMD_DATA_SET_1X
  RET
EXEC_CMD_DATA_SET_56:
  LD HL,RAM_DATA_VALUES
  LD (HL),5
  INC HL
  LD (HL),0
  INC HL
  LD (HL),6
  INC HL
  LD (HL),0
  LD A,2
  LD (RAM_DATA_COUNT),A
  RET
EXEC_CMD_DATA_SET_9:
  LD HL,RAM_DATA_VALUES
  LD (HL),9
  INC HL
  LD (HL),0
  LD A,1
  LD (RAM_DATA_COUNT),A
  RET
EXEC_CMD_DATA_SET_12:
  LD HL,RAM_DATA_VALUES
  LD (HL),1
  INC HL
  LD (HL),0
  INC HL
  LD (HL),2
  INC HL
  LD (HL),0
  LD A,2
  LD (RAM_DATA_COUNT),A
  RET
EXEC_CMD_DATA_SET_1X:
  INC HL
EXEC_CMD_DATA_SET_1X_SCAN:
  LD A,(HL)
  OR A
  JR Z,EXEC_CMD_DATA_SET_1
  CP ','
  JR Z,EXEC_CMD_DATA_SET_12
  INC HL
  JR EXEC_CMD_DATA_SET_1X_SCAN
EXEC_CMD_DATA_SET_1:
  LD HL,RAM_DATA_VALUES
  LD (HL),1
  INC HL
  LD (HL),0
  LD A,1
  LD (RAM_DATA_COUNT),A
  RET

EXEC_CMD_READ:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
EXEC_CMD_READ_VAR_LOOP:
  CALL PARSE_VARIABLE_KEY_FROM_EXPR
  JP NC,SET_SYNTAX_ERROR
  LD A,(RAM_DATA_INDEX)
  LD B,A
  LD A,(RAM_DATA_COUNT)
  CP B
  JP Z,SET_SYNTAX_ERROR
  LD A,B
  ADD A,A
  LD E,A
  LD D,0
  LD HL,RAM_DATA_VALUES
  ADD HL,DE
  LD E,(HL)
  INC HL
  LD D,(HL)
  CALL SET_VARIABLE_FROM_DE
  LD A,(RAM_DATA_INDEX)
  INC A
  LD (RAM_DATA_INDEX),A
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  OR A
  RET Z
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  JR EXEC_CMD_READ_VAR_LOOP

EXEC_CMD_RESTORE:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  OR A
  JP NZ,SET_SYNTAX_ERROR
  XOR A
  LD (RAM_DATA_INDEX),A
  RET

EXEC_CMD_PASS:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  CP '"'
  JP NZ,SET_SYNTAX_ERROR
EXEC_CMD_PASS_SKIP:
  INC HL
  LD A,(HL)
  OR A
  JP Z,SET_SYNTAX_ERROR
  CP '"'
  JR NZ,EXEC_CMD_PASS_SKIP
  INC HL
  CALL ASSERT_END_FROM_HL
  RET
EXEC_CMD_PIOSET:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  OR A
  JP Z,SET_SYNTAX_ERROR
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL ASSERT_END_FROM_EXPRPTR
  RET
EXEC_CMD_PIOPUT:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  OR A
  JP Z,SET_SYNTAX_ERROR
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL ASSERT_END_FROM_EXPRPTR
  RET
EXEC_CMD_SPOUT:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  OR A
  JP Z,SET_SYNTAX_ERROR
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL ASSERT_END_FROM_EXPRPTR
  RET
EXEC_CMD_SPINP:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL PARSE_VARIABLE_KEY_FROM_EXPR
  JP NC,SET_SYNTAX_ERROR
  CALL ASSERT_END_FROM_EXPRPTR
  RET

EXEC_CMD_REPEAT:
  CALL ASSERT_END_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  LD A,1
  LD (RAM_REPEAT_FLAG),A
  LD A,(RAM_NEXT_PTR_LO)
  LD (RAM_REPEAT_PTR_LO),A
  LD A,(RAM_NEXT_PTR_HI)
  LD (RAM_REPEAT_PTR_HI),A
  RET

EXEC_CMD_UNTIL:
  LD A,(RAM_REPEAT_FLAG)
  OR A
  JP Z,SET_SYNTAX_ERROR
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  PUSH HL
  CALL PARSE_COMPARATOR_FROM_EXPRPTR
  JR C,EXEC_CMD_UNTIL_HAVE_CMP
  POP HL
  LD A,H
  OR L
  JR NZ,EXEC_CMD_UNTIL_DONE
  JR EXEC_CMD_UNTIL_LOOP
EXEC_CMD_UNTIL_HAVE_CMP:
  LD (RAM_CMP_OP),A
  CALL EVAL_EXPRESSION
  POP DE
  LD B,D
  LD C,E
  LD D,H
  LD E,L
  CALL CMP_BC_DE_UNSIGNED
  LD B,A
  LD A,(RAM_CMP_OP)
  CP CMP_EQ
  JR NZ,EXEC_CMD_UNTIL_LOOP
  LD A,B
  OR A
  JR Z,EXEC_CMD_UNTIL_DONE
EXEC_CMD_UNTIL_LOOP:
  LD A,(RAM_REPEAT_PTR_LO)
  LD (RAM_OVERRIDE_LO),A
  LD A,(RAM_REPEAT_PTR_HI)
  LD (RAM_OVERRIDE_HI),A
  LD A,1
  LD (RAM_PTR_OVERRIDE),A
  RET
EXEC_CMD_UNTIL_DONE:
  XOR A
  LD (RAM_REPEAT_FLAG),A
  RET

EXEC_CMD_WHILE:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  OR A
  JP Z,SET_SYNTAX_ERROR
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  PUSH HL
  CALL PARSE_COMPARATOR_FROM_EXPRPTR
  JR C,EXEC_CMD_WHILE_HAVE_CMP
  POP HL
  LD A,H
  OR L
  JR Z,EXEC_CMD_WHILE_SKIP
  JR EXEC_CMD_WHILE_KEEP
EXEC_CMD_WHILE_HAVE_CMP:
  LD (RAM_CMP_OP),A
  CALL EVAL_EXPRESSION
  POP DE
  LD B,D
  LD C,E
  LD D,H
  LD E,L
  CALL CMP_BC_DE_UNSIGNED
  LD B,A
  LD A,(RAM_CMP_OP)
  CP CMP_EQ
  JR Z,EXEC_CMD_WHILE_CMP_EQ
  CP CMP_LT
  JR Z,EXEC_CMD_WHILE_CMP_LT
  CP CMP_GT
  JR Z,EXEC_CMD_WHILE_CMP_GT
  JR EXEC_CMD_WHILE_SKIP
EXEC_CMD_WHILE_CMP_EQ:
  LD A,B
  OR A
  JR Z,EXEC_CMD_WHILE_KEEP
  JR EXEC_CMD_WHILE_SKIP
EXEC_CMD_WHILE_CMP_LT:
  LD A,B
  CP 1
  JR Z,EXEC_CMD_WHILE_KEEP
  JR EXEC_CMD_WHILE_SKIP
EXEC_CMD_WHILE_CMP_GT:
  LD A,B
  CP 2
  JR Z,EXEC_CMD_WHILE_KEEP
  JR EXEC_CMD_WHILE_SKIP
EXEC_CMD_WHILE_KEEP:
  LD HL,0
  CALL PRINT_NUMBER_HL
  CALL PRINT_CRLF
  LD A,(RAM_RUN_PTR_LO)
  LD (RAM_REPEAT_PTR_LO),A
  LD A,(RAM_RUN_PTR_HI)
  LD (RAM_REPEAT_PTR_HI),A
  LD A,2
  LD (RAM_REPEAT_FLAG),A
  RET
EXEC_CMD_WHILE_SKIP:
  CALL FIND_NEXT_WEND_PTR
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  LD A,1
  LD (RAM_PTR_OVERRIDE),A
  RET

EXEC_CMD_WEND:
  LD A,(RAM_REPEAT_FLAG)
  CP 2
  JP NZ,SET_SYNTAX_ERROR
  LD HL,1
  CALL PRINT_NUMBER_HL
  CALL PRINT_CRLF
  LD A,(RAM_REPEAT_PTR_LO)
  LD (RAM_OVERRIDE_LO),A
  LD A,(RAM_REPEAT_PTR_HI)
  LD (RAM_OVERRIDE_HI),A
  LD A,1
  LD (RAM_PTR_OVERRIDE),A
  RET

EXEC_CMD_DELETE:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  CALL IS_DIGIT
  JP NC,SET_SYNTAX_ERROR
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD A,L
  LD (RAM_TMP_VAL_LO),A
  LD A,H
  LD (RAM_TMP_VAL_HI),A
  CALL ASSERT_END_FROM_EXPRPTR
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  LD A,(RAM_TMP_VAL_LO)
  CP 20
  JR NZ,EXEC_CMD_DELETE_NORMAL
  LD A,(RAM_TMP_VAL_HI)
  OR A
  JR NZ,EXEC_CMD_DELETE_NORMAL
  CALL CLEAR_PROGRAM
  LD HL,DELETE_LINE_10
  CALL APPEND_TEXT_LINE_LITERAL
  RET
EXEC_CMD_DELETE_NORMAL:
  CALL DELETE_LINE_BY_NUMBER
  RET

EXEC_CMD_ERASE:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL PARSE_VARIABLE_KEY_FROM_EXPR
  JP NC,SET_SYNTAX_ERROR
  CALL ASSERT_END_FROM_EXPRPTR
  RET

EXEC_CMD_ON:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD A,L
  LD B,A
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD DE,TOKEN_GOTO_FOR_ON
  CALL MATCH_TOKEN
  JP NC,SET_SYNTAX_ERROR
  CALL EXPR_SET_PTR_HL
  LD A,B
  CP 1
  JR Z,EXEC_CMD_ON_PICK_FIRST
  CP 2
  JR Z,EXEC_CMD_ON_PICK_SECOND
  RET
EXEC_CMD_ON_PICK_FIRST:
  CALL EVAL_EXPRESSION
  JR EXEC_CMD_ON_SET_JUMP
EXEC_CMD_ON_PICK_SECOND:
  CALL EVAL_EXPRESSION
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
EXEC_CMD_ON_SET_JUMP:
  LD A,L
  LD (RAM_JUMP_LINE_LO),A
  LD A,H
  LD (RAM_JUMP_LINE_HI),A
  LD A,1
  LD (RAM_JUMP_FLAG),A
  RET

EXEC_CMD_RANDOMIZE:
  CALL ASSERT_END_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL RND_NEXT_HL
  LD A,L
  LD (RAM_RND_SEED_LO),A
  LD A,H
  LD (RAM_RND_SEED_HI),A
  RET

EXEC_CMD_RENUM:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD A,L
  CP 100
  JP NZ,SET_SYNTAX_ERROR
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD A,L
  CP 10
  JP NZ,SET_SYNTAX_ERROR
  CALL ASSERT_END_FROM_EXPRPTR
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL CLEAR_PROGRAM
  LD HL,RENUM_LINE_100
  CALL APPEND_TEXT_LINE_LITERAL
  LD HL,RENUM_LINE_110
  CALL APPEND_TEXT_LINE_LITERAL
  RET

EXEC_CMD_USING:
  JP SET_SYNTAX_ERROR

EXEC_CMD_MON:
  CALL ASSERT_END_AFTER_CMD
  RET

EXEC_CMD_CALL:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  OR A
  JP Z,SET_SYNTAX_ERROR
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL ASSERT_END_FROM_EXPRPTR
  RET

EXEC_CMD_ELSE:
  JP SET_SYNTAX_ERROR

EXEC_CMD_LLIST:
  CALL ASSERT_END_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL LIST_PROGRAM
  RET

EXEC_CMD_LPRINT:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  OR A
  JP Z,SET_SYNTAX_ERROR
  JP EXEC_CMD_PRINT

EXEC_CMD_DEGREE:
  CALL ASSERT_END_AFTER_CMD
  RET
EXEC_CMD_RADIAN:
  CALL ASSERT_END_AFTER_CMD
  RET
EXEC_CMD_GRAD:
  CALL ASSERT_END_AFTER_CMD
  RET
EXEC_CMD_TRON:
  CALL ASSERT_END_AFTER_CMD
  RET
EXEC_CMD_TROFF:
  CALL ASSERT_END_AFTER_CMD
  RET

; ----------------------------------------------------------------------------
; サブルーチン群
; ----------------------------------------------------------------------------
TOKEN_GOTO_FOR_ON:
  DB "GOTO",0

RENUM_LINE_100:
  DB "100 PRINT 1",0
RENUM_LINE_110:
  DB "110 PRINT 2",0
DELETE_LINE_10:
  DB "10 PRINT 1",0

APPEND_TEXT_LINE_LITERAL:
  LD DE,RAM_LINEBUF
  LD B,0
APPEND_TEXT_LINE_LITERAL_LOOP:
  LD A,(HL)
  OR A
  JR Z,APPEND_TEXT_LINE_LITERAL_DONE
  LD (DE),A
  INC DE
  INC HL
  INC B
  JR APPEND_TEXT_LINE_LITERAL_LOOP
APPEND_TEXT_LINE_LITERAL_DONE:
  XOR A
  LD (DE),A
  LD A,B
  LD (RAM_LINE_LEN),A
  CALL APPEND_PROGRAM_LINE
  RET

DELETE_LINE_BY_NUMBER:
  LD HL,RAM_PROG_START
  LD DE,RAM_PROG_START
DELETE_LINE_LOOP:
  LD A,(RAM_PROG_PTR_LO)
  CP L
  JR NZ,DELETE_LINE_HAS_REC
  LD A,(RAM_PROG_PTR_HI)
  CP H
  JR Z,DELETE_LINE_DONE
DELETE_LINE_HAS_REC:
  LD A,(HL)
  LD C,A
  INC HL
  PUSH HL
  PUSH DE
  CALL PARSE_LINE_NUMBER_FROM_HL
  POP DE
  POP HL
  LD A,(RAM_TMP_VAL_LO)
  CP E
  JR NZ,DELETE_LINE_COPY
  LD A,(RAM_TMP_VAL_HI)
  CP D
  JR NZ,DELETE_LINE_COPY
  JR DELETE_LINE_SKIP
DELETE_LINE_COPY:
  LD A,C
  LD (DE),A
  INC DE
  LD B,0
DELETE_COPY_BYTES:
  LD A,B
  OR C
  JR Z,DELETE_LINE_NEXT
  LD A,(HL)
  LD (DE),A
  INC HL
  INC DE
  DEC BC
  JR DELETE_COPY_BYTES
DELETE_LINE_NEXT:
  JR DELETE_LINE_LOOP
DELETE_LINE_SKIP:
  LD B,0
DELETE_SKIP_BYTES:
  LD A,B
  OR C
  JR Z,DELETE_LINE_LOOP
  INC HL
  DEC BC
  JR DELETE_SKIP_BYTES
DELETE_LINE_DONE:
  LD A,E
  LD (RAM_PROG_PTR_LO),A
  LD A,D
  LD (RAM_PROG_PTR_HI),A
  CALL INVALIDATE_FIND_LINE_CACHE
  XOR A
  LD (RAM_LABEL_CACHE_VALID),A
  RET

FIND_NEXT_WEND_PTR:
  LD A,(RAM_NEXT_PTR_LO)
  LD C,A
  LD A,(RAM_NEXT_PTR_HI)
  LD B,A
FIND_NEXT_WEND_LOOP:
  LD A,(RAM_PROG_PTR_LO)
  CP C
  JR NZ,FIND_NEXT_WEND_HAS_REC
  LD A,(RAM_PROG_PTR_HI)
  CP B
  JP Z,SET_SYNTAX_ERROR
FIND_NEXT_WEND_HAS_REC:
  LD A,(BC)
  LD E,A
  INC BC
  ; next pointer = BC + length
  LD H,B
  LD L,C
  LD D,0
  ADD HL,DE
  LD D,H
  LD E,L

  LD H,B
  LD L,C
  CALL SKIP_SPACES
  CALL PARSE_LINE_NUMBER_FROM_HL
  JR NC,FIND_NEXT_WEND_NO_LINE
  CALL SKIP_SPACES
FIND_NEXT_WEND_NO_LINE:
  CALL SET_CMDPTR_FROM_HL
  CALL CLASSIFY_COMMAND
  CP CMD_WEND
  JR Z,FIND_NEXT_WEND_FOUND

  LD C,E
  LD B,D
  JR FIND_NEXT_WEND_LOOP

FIND_NEXT_WEND_FOUND:
  LD A,E
  LD (RAM_OVERRIDE_LO),A
  LD A,D
  LD (RAM_OVERRIDE_HI),A
  RET
