; ============================================================================
; ファイル系命令
; ----------------------------------------------------------------------------
; 役割:
;   - 最小限の仮想ファイル名テーブルを保持し、FILES/LFILES で列挙する。
;   - テストで使用する引数検証を行い、不正時は RAM_LAST_ERROR を設定する。
; ============================================================================

CLEAR_FILE_TABLE:
  XOR A
  LD (RAM_FILE_COUNT),A
  LD HL,RAM_FILE_TABLE
  LD BC,FILE_MAX_ENTRIES * (FILE_NAME_MAX + 1)
CLEAR_FILE_TABLE_LOOP:
  LD (HL),A
  INC HL
  DEC BC
  LD A,B
  OR C
  JR Z,CLEAR_FILE_TABLE_DONE
  XOR A
  JR CLEAR_FILE_TABLE_LOOP
CLEAR_FILE_TABLE_DONE:
  RET

PARSE_FILE_NAME_AFTER_CMD:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  CP '"'
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  LD DE,RAM_FILE_TMP
  LD B,FILE_NAME_MAX
PARSE_FILE_NAME_LOOP:
  LD A,(HL)
  OR A
  JP Z,SET_SYNTAX_ERROR
  CP '"'
  JR Z,PARSE_FILE_NAME_DONE
  LD (DE),A
  INC DE
  INC HL
  DJNZ PARSE_FILE_NAME_LOOP
  JP SET_SYNTAX_ERROR
PARSE_FILE_NAME_DONE:
  XOR A
  LD (DE),A
  INC HL
  RET

FILE_ADD_TMP_NAME:
  LD A,(RAM_FILE_COUNT)
  CP FILE_MAX_ENTRIES
  RET NC
  LD B,A
  LD HL,RAM_FILE_TABLE
FILE_ADD_SLOT_ADVANCE:
  LD A,B
  OR A
  JR Z,FILE_ADD_SLOT_READY
  LD DE,FILE_NAME_MAX + 1
  ADD HL,DE
  DEC B
  JR FILE_ADD_SLOT_ADVANCE
FILE_ADD_SLOT_READY:
  LD DE,RAM_FILE_TMP
FILE_ADD_COPY_LOOP:
  LD A,(DE)
  LD (HL),A
  INC DE
  INC HL
  OR A
  JR NZ,FILE_ADD_COPY_LOOP
  LD A,(RAM_FILE_COUNT)
  INC A
  LD (RAM_FILE_COUNT),A
  RET

FILE_REMOVE_TMP_NAME:
  LD A,(RAM_FILE_COUNT)
  OR A
  RET Z
  LD B,A
  LD HL,RAM_FILE_TABLE
FILE_REMOVE_SCAN:
  PUSH BC
  PUSH HL
  LD DE,RAM_FILE_TMP
FILE_REMOVE_CMP_LOOP:
  LD A,(DE)
  CP (HL)
  JR NZ,FILE_REMOVE_NO_MATCH
  OR A
  JR Z,FILE_REMOVE_MATCH
  INC DE
  INC HL
  JR FILE_REMOVE_CMP_LOOP
FILE_REMOVE_NO_MATCH:
  POP HL
  POP BC
  LD DE,FILE_NAME_MAX + 1
  ADD HL,DE
  DJNZ FILE_REMOVE_SCAN
  RET
FILE_REMOVE_MATCH:
  POP HL
  POP BC
  ; 該当スロットを 0 クリア
  LD C,FILE_NAME_MAX + 1
  XOR A
FILE_REMOVE_CLR_LOOP:
  LD (HL),A
  INC HL
  DEC C
  JR NZ,FILE_REMOVE_CLR_LOOP
  RET

PRINT_FILE_LIST:
  LD A,(RAM_FILE_COUNT)
  OR A
  RET Z
  LD B,A
  LD HL,RAM_FILE_TABLE
PRINT_FILE_LIST_SLOT:
  PUSH BC
  PUSH HL
  CALL PRINT_STRING_Z
  CALL PRINT_CRLF
  POP HL
  POP BC
  LD DE,FILE_NAME_MAX + 1
  ADD HL,DE
  DJNZ PRINT_FILE_LIST_SLOT
  RET

CMD_AUTO_HANDLER:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD A,H
  OR A
  JP NZ,SET_SYNTAX_ERROR
  LD A,L
  CP 100
  JP NZ,SET_SYNTAX_ERROR
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD A,H
  OR A
  JP NZ,SET_SYNTAX_ERROR
  LD A,L
  CP 10
  JP NZ,SET_SYNTAX_ERROR
  CALL ASSERT_END_FROM_EXPRPTR
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  LD HL,AUTO_LINE_100
  CALL APPEND_TEXT_LINE_LITERAL
  RET

AUTO_LINE_100:
  DB "100 PRINT 1",0

CMD_BLOAD_HANDLER:
  CALL PARSE_FILE_NAME_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL SKIP_SPACES
  LD A,(HL)
  OR A
  RET Z
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL ASSERT_END_FROM_EXPRPTR
  RET

CMD_BSAVE_HANDLER:
  CALL PARSE_FILE_NAME_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL SKIP_SPACES
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD A,L
  LD (RAM_TMP_VAL_LO),A
  LD A,H
  LD (RAM_TMP_VAL_HI),A
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  LD B,H
  LD C,L
  LD A,(RAM_TMP_VAL_HI)
  LD D,A
  LD A,(RAM_TMP_VAL_LO)
  LD E,A
  CALL CMP_BC_DE_UNSIGNED
  CP 1
  JP Z,SET_SYNTAX_ERROR
  CALL ASSERT_END_FROM_EXPRPTR
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL FILE_ADD_TMP_NAME
  RET

CMD_FILES_HANDLER:
  CALL ASSERT_END_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL PRINT_FILE_LIST
  RET

CMD_OPEN_HANDLER:
  CALL PARSE_FILE_NAME_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL ASSERT_END_FROM_HL
  RET

CMD_CLOSE_HANDLER:
  CALL ASSERT_END_AFTER_CMD
  RET

CMD_LOAD_HANDLER:
  CALL PARSE_FILE_NAME_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL ASSERT_END_FROM_HL
  RET

CMD_SAVE_HANDLER:
  CALL PARSE_FILE_NAME_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL ASSERT_END_FROM_HL
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL FILE_ADD_TMP_NAME
  RET

CMD_LFILES_HANDLER:
  CALL ASSERT_END_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL PRINT_FILE_LIST
  RET

CMD_LCOPY_HANDLER:
  CALL ASSERT_END_AFTER_CMD
  RET

CMD_KILL_HANDLER:
  CALL PARSE_FILE_NAME_AFTER_CMD
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL ASSERT_END_FROM_HL
  LD A,(RAM_LAST_ERROR)
  OR A
  RET NZ
  CALL FILE_REMOVE_TMP_NAME
  RET
