; ============================================================================
; グラフィックス系命令スタブ
; ----------------------------------------------------------------------------
; 役割:
;   - 描画命令群の入口を保持する。
;   - 現段階は共通スタブで受け、将来ルーチン差し替え可能な形にする。
; ============================================================================

CMD_HDCOPY_HANDLER:
  CALL ASSERT_END_AFTER_CMD
  RET

CMD_PAINT_HANDLER:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL ASSERT_END_FROM_EXPRPTR
  RET

CMD_CIRCLE_HANDLER:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL ASSERT_END_FROM_EXPRPTR
  RET

CMD_GCURSOR_HANDLER:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL ASSERT_END_FROM_EXPRPTR
  RET

CMD_GPRINT_HANDLER:
  CALL LOAD_AFTER_CMD_HL
  CALL SKIP_SPACES
  LD A,(HL)
  OR A
  JP Z,SET_SYNTAX_ERROR
  RET

CMD_LINE_HANDLER:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL ASSERT_END_FROM_EXPRPTR
  RET

CMD_PSET_HANDLER:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL ASSERT_END_FROM_EXPRPTR
  RET

CMD_PRESET_HANDLER:
  CALL LOAD_AFTER_CMD_HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL EXPR_SKIP_SPACES
  CALL EXPR_GET_PTR_HL
  LD A,(HL)
  CP ','
  JP NZ,SET_SYNTAX_ERROR
  INC HL
  CALL EXPR_SET_PTR_HL
  CALL EVAL_EXPRESSION
  CALL ASSERT_END_FROM_EXPRPTR
  RET
