import {
  BIOS_ROM_IMAGE,
  MONITOR_MAIN_LOOP_ADDR,
  MONITOR_PROMPT_RESUME_ADDR
} from './generated/bios_rom';

export {
  BIOS_COLD_BOOT_ADDR,
  BIOS_BOOT_ENTRY,
  BIOS_CHAR_PUT_ENTRY,
  BIOS_CHAR_REPEAT_ENTRY,
  BIOS_CLEAR_SCREEN_ENTRY,
  BIOS_CRLF_ENTRY,
  BIOS_GET_DISPLAY_START_ENTRY,
  BIOS_GET_GLYPH_PTR_ENTRY,
  BIOS_GRAPHICS_WRITE_RAW_ENTRY,
  BIOS_INKEY_ENTRY,
  BIOS_JUMP_TABLE_ENTRY_COUNT,
  BIOS_JUMP_TABLE_START,
  BIOS_MONITOR_MAIN_LOOP_ENTRY,
  BIOS_RESERVED_NOP_BYTES,
  BIOS_ROM_BASE,
  BIOS_SET_CURSOR_ENTRY,
  BIOS_SET_DISPLAY_START_ENTRY,
  BIOS_SHUTDOWN_ENTRY,
  BIOS_STRING_PUT_Z_ENTRY,
  BIOS_WAIT_KEY_ENTRY,
  MONITOR_MAIN_LOOP_ADDR,
  MONITOR_PROMPT_RESUME_ADDR
} from './generated/bios_rom';

export const MONITOR_PROMPT_CURSOR_COL = 2;
export const MONITOR_PROMPT_CURSOR_ROW = 2;
const ROM_SIZE = 0x4000;

export function createMonitorRom(): Uint8Array {
  const rom = new Uint8Array(ROM_SIZE);
  rom.set(BIOS_ROM_IMAGE.subarray(0, Math.min(BIOS_ROM_IMAGE.length, ROM_SIZE)), 0);
  return rom;
}
